format_version: v1.0
type: UniqueComponent
attributes: {id: audio_decoders}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: CONFIG_USE_ADPCM_STREAMING}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '554', y: '24', id: audio_decoders}
