format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_sdspi}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DRV_SDSPI_COMMON_FS_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sdspi, value: 'true'}
  - type: Combo
    attributes: {id: DRV_SDSPI_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sdspi, value: Asynchronous}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_sdspi}
    children:
    - type: Symbols
      children:
      - type: KeyValueSet
        attributes: {id: DRV_SDSPI_CHIP_SELECT_PIN}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '44'}
      - type: Boolean
        attributes: {id: DRV_SDSPI_FS_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: 'true'}
      - type: String
        attributes: {id: DRV_SDSPI_INTERFACE_TYPE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: SPI_PLIB}
      - type: String
        attributes: {id: DRV_SDSPI_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: SPI1}
      - type: Menu
        attributes: {id: DRV_SDSPI_RTOS_MENU}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: Integer
        attributes: {id: DRV_SDSPI_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: '1'}
      - type: Integer
        attributes: {id: DRV_SDSPI_SPEED_HZ}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '10000000'}
      - type: Integer
        attributes: {id: DRV_SDSPI_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdspi_0, value: '1'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_sdspi_SPI_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: spi1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SPI1_SPI}
- type: ElementPosition
  attributes: {x: '649', y: '120', id: drv_sdspi}
