format_version: v1.0
type: UniqueComponent
attributes: {id: drv_usbfs_v1}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: DRV_USB_SOURCE_FILE_DEVICE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: DRV_USB_SOURCE_FILE_HOST}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: USB_DEVICE_VBUS_SENSE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: USB_DRV_HOST_ATTACH_DEBOUNCE_DURATION}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: USB_DRV_HOST_RESET_DUARTION}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: USB_HOST_VBUS_ENABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: USB_HOST_VBUS_ENABLE_PIN_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: VBUS}
  - type: Combo
    attributes: {id: USB_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbfs_v1, value: Host}
- type: ElementPosition
  attributes: {x: '791', y: '5', id: drv_usbfs_v1}
