format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_legato}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: driverInitName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_legato, value: ExternalController}
  - type: Menu
    attributes: {id: rtosMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: gfx_driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_external}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver_external}
- type: ElementPosition
  attributes: {x: '490', y: '317', id: gfx_legato}
