format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_intf_parallel_portgroup}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DMAChannel}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: DelayNOPCount}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: GFX_INTF_PORTGROUP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: GFX_INTF_PORTGROUP_DMA}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: PortGroup}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_mxt_cpro, value: '2'}
  - type: Comment
    attributes: {id: PortGroupDMAComment}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: PortGroupHalf}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: PortGroupQuadrant}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: ReadStrobeControl}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_intf_parallel_portgroup, value: N/A}
  - type: Combo
    attributes: {id: TransferMode}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DMA-CCL}
  - type: Menu
    attributes: {id: TransferModeSettingsMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: UseTimerTrigger}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: WriteStrobeControl}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_intf_parallel_portgroup, value: CCL}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: le_gfx_intf_parallel_portgroup}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_external}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: Parallel Display Interface}
- type: ElementPosition
  attributes: {x: '3', y: '398', id: le_gfx_intf_parallel_portgroup}
