format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_driver_external}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: BaseDriverType}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ILI9488}
  - type: Hex
    attributes: {id: Command0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '58'}
  - type: String
    attributes: {id: Command0Comment}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: Pixel Format Set}
  - type: Hex
    attributes: {id: Command0Parm0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '5'}
  - type: Integer
    attributes: {id: Command0ParmsCount}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '1'}
  - type: Hex
    attributes: {id: Command1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '233'}
  - type: String
    attributes: {id: Command1Comment}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: Set Image Function}
  - type: Hex
    attributes: {id: Command1Parm0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '1'}
  - type: Integer
    attributes: {id: Command1ParmsCount}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '1'}
  - type: Hex
    attributes: {id: Command2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '176'}
  - type: String
    attributes: {id: Command2Comment}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: Interface Mode Control}
  - type: Hex
    attributes: {id: Command2Parm0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '0'}
  - type: Integer
    attributes: {id: Command2ParmsCount}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '1'}
  - type: Hex
    attributes: {id: Command3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '54'}
  - type: String
    attributes: {id: Command3Comment}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: Memory Access Control}
  - type: Hex
    attributes: {id: Command3Parm0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '72'}
      - type: User
        attributes: {value: '40'}
  - type: Integer
    attributes: {id: Command3ParmsCount}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '1'}
  - type: Hex
    attributes: {id: Command4}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '17'}
  - type: String
    attributes: {id: Command4Comment}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: Sleep Out}
  - type: Integer
    attributes: {id: Command4ParmsCount}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '0'}
  - type: Hex
    attributes: {id: Command5}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '41'}
  - type: String
    attributes: {id: Command5Comment}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: Display On}
  - type: Integer
    attributes: {id: Command5ParmsCount}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '0'}
  - type: String
    attributes: {id: ControllerName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: ILI9488}
  - type: Combo
    attributes: {id: DataWriteSize}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '8'}
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '480'}
      - type: User
        attributes: {value: '320'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '320'}
      - type: User
        attributes: {value: '480'}
  - type: Integer
    attributes: {id: InitCommandsCount}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '6'}
  - type: Hex
    attributes: {id: MemoryWriteCommand}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '44'}
  - type: Comment
    attributes: {id: PixelDataInfoString16bit}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: PixelDataInfoString8bit2byteNorm}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: PixelDataTxSize8Bit}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: PostResetDelay}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '30'}
  - type: Hex
    attributes: {id: SetXAddressCommand}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '42'}
  - type: Hex
    attributes: {id: SetYAddressCommand}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_external, value: '43'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Graphics Display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_disp_mxt_cpro_320x480}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_display}
  - type: DirectDependency
    attributes: {id: Parallel Display Interface}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_intf_parallel_portgroup}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: le_gfx_intf_parallel_portgroup}
  - type: DirectCapability
    attributes: {id: gfx_driver_external}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_legato}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver}
- type: ElementPosition
  attributes: {x: '255', y: '255', id: le_gfx_driver_external}
