format_version: v1.0
type: GeneratorComponent
attributes: {id: atecc608}
children:
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: atecc608}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: HAL_INTERFACE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: atecc608_0, value: SERCOM1}
      - type: Hex
        attributes: {id: I2C_ADDR}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: atecc608_0, value: '108'}
          - type: User
            attributes: {value: '192'}
      - type: KeyValueSet
        attributes: {id: INTERFACE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: readOnly}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: atecc608_0, value: '0'}
      - type: KeyValueSet
        attributes: {id: PART_TYPE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '1'}
    - type: Attachments
      children:
      - type: MultiCapability
        attributes: {id: ATECC608_DEP_PLIB_I2C}
        children:
        - type: TargetAttachments
          children:
          - type: TargetAttachment
            attributes: {targetComponentID: sercom1, targetAttachmentID: SERCOM1_I2C}
- type: ElementPosition
  attributes: {x: '170', y: '80', id: atecc608}
