format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: CALLBACK_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32CallbackRegister}
  - type: String
    attributes: {id: COMPARE_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32CompareSet}
  - type: String
    attributes: {id: COUNTER_GET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32CounterGet}
  - type: String
    attributes: {id: FREQUENCY_GET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32FrequencyGet}
  - type: String
    attributes: {id: IRQ_ENUM_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_IRQn}
  - type: String
    attributes: {id: PERIOD_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: ''}
  - type: File
    attributes: {id: RTC_CLOCK_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: File
    attributes: {id: RTC_INSTANCE_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: KeyValueSet
    attributes: {id: RTC_MODE0_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: RTC_MODULE_SELECTION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: File
    attributes: {id: RTC_SYS_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_DEFINITIONS_H_INCLUDES}
  - type: File
    attributes: {id: RTC_SYS_INIT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_INIT_C_SYS_INITIALIZE_PERIPHERALS}
  - type: File
    attributes: {id: RTC_TIMER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: NON_SECURE}
  - type: String
    attributes: {id: TIMER_PERIOD_MAX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '0xFFFFFFFF'}
  - type: String
    attributes: {id: TIMER_START_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32Start}
  - type: String
    attributes: {id: TIMER_STOP_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32Stop}
  - type: Integer
    attributes: {id: TIMER_WIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '32'}
- type: ElementPosition
  attributes: {x: '19', y: '266', id: rtc}
