format_version: v1.0
type: UniqueComponent
attributes: {id: nvmctrl}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: NVMCTRL_AHB0_CACHE_DISABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: NVMCTRL_AHB1_CACHE_DISABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: NVMCTRL_CTRLA_POWER_REDUCTION_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: NVM_RWS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvmctrl, value: '0'}
- type: ElementPosition
  attributes: {x: '11', y: '16', id: nvmctrl}
