# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_capabilities/V3AlexaCookingPresetController.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3PresetName_pb2 as v3avs__types_dot_V3PresetName__pb2
from v3avs_types import V3CookingMode_pb2 as v3avs__types_dot_V3CookingMode__pb2
from v3avs_types import V3FoodItem_pb2 as v3avs__types_dot_V3FoodItem__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_capabilities/V3AlexaCookingPresetController.proto',
  package='v3avs_capabilities',
  syntax='proto3',
  serialized_pb=_b('\n7v3avs_capabilities/V3AlexaCookingPresetController.proto\x12\x12v3avs_capabilities\x1a\x1ev3avs_types/V3PresetName.proto\x1a\x1fv3avs_types/V3CookingMode.proto\x1a\x1cv3avs_types/V3FoodItem.proto\"\xa7\x04\n\x1eV3AlexaCookingPresetController\x1a\xcb\x01\n\tDirective\x12X\n\x0e\x64irective_name\x18\x01 \x01(\x0e\x32@.v3avs_capabilities.V3AlexaCookingPresetController.DirectiveName\x12Y\n\x0e\x63ook_by_preset\x18\x02 \x01(\x0b\x32?.v3avs_capabilities.V3AlexaCookingPresetController.CookByPresetH\x00\x42\t\n\x07payload\x1a\x9c\x01\n\x0c\x43ookByPreset\x12.\n\x0bpreset_name\x18\x01 \x01(\x0b\x32\x19.v3avs_types.V3PresetName\x12\x30\n\x0c\x63ooking_mode\x18\x02 \x01(\x0b\x32\x1a.v3avs_types.V3CookingMode\x12*\n\tfood_item\x18\x03 \x01(\x0b\x32\x17.v3avs_types.V3FoodItem\x1a\x07\n\x05\x45vent\x1a\x44\n\x12PresetNameProperty\x12.\n\x0bpreset_name\x18\x01 \x01(\x0b\x32\x19.v3avs_types.V3PresetName\"#\n\rDirectiveName\x12\x12\n\x0e\x43OOK_BY_PRESET\x10\x00\"$\n\x0cPropertyName\x12\x14\n\x10PRESET_NAME_PROP\x10\x00\x42J\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\x1c\x41lexaCookingPresetControllerb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3PresetName__pb2.DESCRIPTOR,v3avs__types_dot_V3CookingMode__pb2.DESCRIPTOR,v3avs__types_dot_V3FoodItem__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVENAME = _descriptor.EnumDescriptor(
  name='DirectiveName',
  full_name='v3avs_capabilities.V3AlexaCookingPresetController.DirectiveName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COOK_BY_PRESET', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=653,
  serialized_end=688,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVENAME)

_V3ALEXACOOKINGPRESETCONTROLLER_PROPERTYNAME = _descriptor.EnumDescriptor(
  name='PropertyName',
  full_name='v3avs_capabilities.V3AlexaCookingPresetController.PropertyName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRESET_NAME_PROP', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=690,
  serialized_end=726,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXACOOKINGPRESETCONTROLLER_PROPERTYNAME)


_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE = _descriptor.Descriptor(
  name='Directive',
  full_name='v3avs_capabilities.V3AlexaCookingPresetController.Directive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='directive_name', full_name='v3avs_capabilities.V3AlexaCookingPresetController.Directive.directive_name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cook_by_preset', full_name='v3avs_capabilities.V3AlexaCookingPresetController.Directive.cook_by_preset', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='v3avs_capabilities.V3AlexaCookingPresetController.Directive.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=210,
  serialized_end=413,
)

_V3ALEXACOOKINGPRESETCONTROLLER_COOKBYPRESET = _descriptor.Descriptor(
  name='CookByPreset',
  full_name='v3avs_capabilities.V3AlexaCookingPresetController.CookByPreset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preset_name', full_name='v3avs_capabilities.V3AlexaCookingPresetController.CookByPreset.preset_name', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cooking_mode', full_name='v3avs_capabilities.V3AlexaCookingPresetController.CookByPreset.cooking_mode', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='food_item', full_name='v3avs_capabilities.V3AlexaCookingPresetController.CookByPreset.food_item', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=572,
)

_V3ALEXACOOKINGPRESETCONTROLLER_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='v3avs_capabilities.V3AlexaCookingPresetController.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=581,
)

_V3ALEXACOOKINGPRESETCONTROLLER_PRESETNAMEPROPERTY = _descriptor.Descriptor(
  name='PresetNameProperty',
  full_name='v3avs_capabilities.V3AlexaCookingPresetController.PresetNameProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preset_name', full_name='v3avs_capabilities.V3AlexaCookingPresetController.PresetNameProperty.preset_name', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=651,
)

_V3ALEXACOOKINGPRESETCONTROLLER = _descriptor.Descriptor(
  name='V3AlexaCookingPresetController',
  full_name='v3avs_capabilities.V3AlexaCookingPresetController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE, _V3ALEXACOOKINGPRESETCONTROLLER_COOKBYPRESET, _V3ALEXACOOKINGPRESETCONTROLLER_EVENT, _V3ALEXACOOKINGPRESETCONTROLLER_PRESETNAMEPROPERTY, ],
  enum_types=[
    _V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVENAME,
    _V3ALEXACOOKINGPRESETCONTROLLER_PROPERTYNAME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=726,
)

_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE.fields_by_name['directive_name'].enum_type = _V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVENAME
_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE.fields_by_name['cook_by_preset'].message_type = _V3ALEXACOOKINGPRESETCONTROLLER_COOKBYPRESET
_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE.containing_type = _V3ALEXACOOKINGPRESETCONTROLLER
_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE.oneofs_by_name['payload'].fields.append(
  _V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE.fields_by_name['cook_by_preset'])
_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE.fields_by_name['cook_by_preset'].containing_oneof = _V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE.oneofs_by_name['payload']
_V3ALEXACOOKINGPRESETCONTROLLER_COOKBYPRESET.fields_by_name['preset_name'].message_type = v3avs__types_dot_V3PresetName__pb2._V3PRESETNAME
_V3ALEXACOOKINGPRESETCONTROLLER_COOKBYPRESET.fields_by_name['cooking_mode'].message_type = v3avs__types_dot_V3CookingMode__pb2._V3COOKINGMODE
_V3ALEXACOOKINGPRESETCONTROLLER_COOKBYPRESET.fields_by_name['food_item'].message_type = v3avs__types_dot_V3FoodItem__pb2._V3FOODITEM
_V3ALEXACOOKINGPRESETCONTROLLER_COOKBYPRESET.containing_type = _V3ALEXACOOKINGPRESETCONTROLLER
_V3ALEXACOOKINGPRESETCONTROLLER_EVENT.containing_type = _V3ALEXACOOKINGPRESETCONTROLLER
_V3ALEXACOOKINGPRESETCONTROLLER_PRESETNAMEPROPERTY.fields_by_name['preset_name'].message_type = v3avs__types_dot_V3PresetName__pb2._V3PRESETNAME
_V3ALEXACOOKINGPRESETCONTROLLER_PRESETNAMEPROPERTY.containing_type = _V3ALEXACOOKINGPRESETCONTROLLER
_V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVENAME.containing_type = _V3ALEXACOOKINGPRESETCONTROLLER
_V3ALEXACOOKINGPRESETCONTROLLER_PROPERTYNAME.containing_type = _V3ALEXACOOKINGPRESETCONTROLLER
DESCRIPTOR.message_types_by_name['V3AlexaCookingPresetController'] = _V3ALEXACOOKINGPRESETCONTROLLER

V3AlexaCookingPresetController = _reflection.GeneratedProtocolMessageType('V3AlexaCookingPresetController', (_message.Message,), dict(

  Directive = _reflection.GeneratedProtocolMessageType('Directive', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGPRESETCONTROLLER_DIRECTIVE,
    __module__ = 'v3avs_capabilities.V3AlexaCookingPresetController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingPresetController.Directive)
    ))
  ,

  CookByPreset = _reflection.GeneratedProtocolMessageType('CookByPreset', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGPRESETCONTROLLER_COOKBYPRESET,
    __module__ = 'v3avs_capabilities.V3AlexaCookingPresetController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingPresetController.CookByPreset)
    ))
  ,

  Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGPRESETCONTROLLER_EVENT,
    __module__ = 'v3avs_capabilities.V3AlexaCookingPresetController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingPresetController.Event)
    ))
  ,

  PresetNameProperty = _reflection.GeneratedProtocolMessageType('PresetNameProperty', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGPRESETCONTROLLER_PRESETNAMEPROPERTY,
    __module__ = 'v3avs_capabilities.V3AlexaCookingPresetController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingPresetController.PresetNameProperty)
    ))
  ,
  DESCRIPTOR = _V3ALEXACOOKINGPRESETCONTROLLER,
  __module__ = 'v3avs_capabilities.V3AlexaCookingPresetController_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingPresetController)
  ))
_sym_db.RegisterMessage(V3AlexaCookingPresetController)
_sym_db.RegisterMessage(V3AlexaCookingPresetController.Directive)
_sym_db.RegisterMessage(V3AlexaCookingPresetController.CookByPreset)
_sym_db.RegisterMessage(V3AlexaCookingPresetController.Event)
_sym_db.RegisterMessage(V3AlexaCookingPresetController.PresetNameProperty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\034AlexaCookingPresetController'))
# @@protoc_insertion_point(module_scope)
