# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_capabilities/V3AlexaInventoryLevelUsageSensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3InventoryConsumed_pb2 as v3avs__types_dot_V3InventoryConsumed__pb2
from v3avs_types import V3InventoryReplaced_pb2 as v3avs__types_dot_V3InventoryReplaced__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_capabilities/V3AlexaInventoryLevelUsageSensor.proto',
  package='v3avs_capabilities',
  syntax='proto3',
  serialized_pb=_b('\n9v3avs_capabilities/V3AlexaInventoryLevelUsageSensor.proto\x12\x12v3avs_capabilities\x1a%v3avs_types/V3InventoryConsumed.proto\x1a%v3avs_types/V3InventoryReplaced.proto\"\xb4\x04\n V3AlexaInventoryLevelUsageSensor\x1a\xac\x02\n\x05\x45vent\x12L\n\x04name\x18\x01 \x01(\x0e\x32>.v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.EventName\x12\x64\n\x12inventory_consumed\x18\x02 \x01(\x0b\x32\x46.v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.InventoryConsumedH\x00\x12\x64\n\x12inventory_replaced\x18\x03 \x01(\x0b\x32\x46.v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.InventoryReplacedH\x00\x42\t\n\x07payload\x1aQ\n\x11InventoryConsumed\x12<\n\x12inventory_consumed\x18\x01 \x01(\x0b\x32 .v3avs_types.V3InventoryConsumed\x1aQ\n\x11InventoryReplaced\x12<\n\x12inventory_replaced\x18\x01 \x01(\x0b\x32 .v3avs_types.V3InventoryReplaced\";\n\tEventName\x12\x16\n\x12INVENTORY_CONSUMED\x10\x00\x12\x16\n\x12INVENTORY_REPLACED\x10\x01\x42L\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\x1e\x41lexaInventoryLevelUsageSensorb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3InventoryConsumed__pb2.DESCRIPTOR,v3avs__types_dot_V3InventoryReplaced__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENTNAME = _descriptor.EnumDescriptor(
  name='EventName',
  full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.EventName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVENTORY_CONSUMED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVENTORY_REPLACED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=665,
  serialized_end=724,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENTNAME)


_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.Event.name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory_consumed', full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.Event.inventory_consumed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory_replaced', full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.Event.inventory_replaced', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.Event.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=197,
  serialized_end=497,
)

_V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYCONSUMED = _descriptor.Descriptor(
  name='InventoryConsumed',
  full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.InventoryConsumed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inventory_consumed', full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.InventoryConsumed.inventory_consumed', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=580,
)

_V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYREPLACED = _descriptor.Descriptor(
  name='InventoryReplaced',
  full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.InventoryReplaced',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inventory_replaced', full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.InventoryReplaced.inventory_replaced', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=582,
  serialized_end=663,
)

_V3ALEXAINVENTORYLEVELUSAGESENSOR = _descriptor.Descriptor(
  name='V3AlexaInventoryLevelUsageSensor',
  full_name='v3avs_capabilities.V3AlexaInventoryLevelUsageSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT, _V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYCONSUMED, _V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYREPLACED, ],
  enum_types=[
    _V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENTNAME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=724,
)

_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.fields_by_name['name'].enum_type = _V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENTNAME
_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.fields_by_name['inventory_consumed'].message_type = _V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYCONSUMED
_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.fields_by_name['inventory_replaced'].message_type = _V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYREPLACED
_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.containing_type = _V3ALEXAINVENTORYLEVELUSAGESENSOR
_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.oneofs_by_name['payload'].fields.append(
  _V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.fields_by_name['inventory_consumed'])
_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.fields_by_name['inventory_consumed'].containing_oneof = _V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.oneofs_by_name['payload']
_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.oneofs_by_name['payload'].fields.append(
  _V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.fields_by_name['inventory_replaced'])
_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.fields_by_name['inventory_replaced'].containing_oneof = _V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT.oneofs_by_name['payload']
_V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYCONSUMED.fields_by_name['inventory_consumed'].message_type = v3avs__types_dot_V3InventoryConsumed__pb2._V3INVENTORYCONSUMED
_V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYCONSUMED.containing_type = _V3ALEXAINVENTORYLEVELUSAGESENSOR
_V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYREPLACED.fields_by_name['inventory_replaced'].message_type = v3avs__types_dot_V3InventoryReplaced__pb2._V3INVENTORYREPLACED
_V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYREPLACED.containing_type = _V3ALEXAINVENTORYLEVELUSAGESENSOR
_V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENTNAME.containing_type = _V3ALEXAINVENTORYLEVELUSAGESENSOR
DESCRIPTOR.message_types_by_name['V3AlexaInventoryLevelUsageSensor'] = _V3ALEXAINVENTORYLEVELUSAGESENSOR

V3AlexaInventoryLevelUsageSensor = _reflection.GeneratedProtocolMessageType('V3AlexaInventoryLevelUsageSensor', (_message.Message,), dict(

  Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXAINVENTORYLEVELUSAGESENSOR_EVENT,
    __module__ = 'v3avs_capabilities.V3AlexaInventoryLevelUsageSensor_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.Event)
    ))
  ,

  InventoryConsumed = _reflection.GeneratedProtocolMessageType('InventoryConsumed', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYCONSUMED,
    __module__ = 'v3avs_capabilities.V3AlexaInventoryLevelUsageSensor_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.InventoryConsumed)
    ))
  ,

  InventoryReplaced = _reflection.GeneratedProtocolMessageType('InventoryReplaced', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXAINVENTORYLEVELUSAGESENSOR_INVENTORYREPLACED,
    __module__ = 'v3avs_capabilities.V3AlexaInventoryLevelUsageSensor_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaInventoryLevelUsageSensor.InventoryReplaced)
    ))
  ,
  DESCRIPTOR = _V3ALEXAINVENTORYLEVELUSAGESENSOR,
  __module__ = 'v3avs_capabilities.V3AlexaInventoryLevelUsageSensor_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaInventoryLevelUsageSensor)
  ))
_sym_db.RegisterMessage(V3AlexaInventoryLevelUsageSensor)
_sym_db.RegisterMessage(V3AlexaInventoryLevelUsageSensor.Event)
_sym_db.RegisterMessage(V3AlexaInventoryLevelUsageSensor.InventoryConsumed)
_sym_db.RegisterMessage(V3AlexaInventoryLevelUsageSensor.InventoryReplaced)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\036AlexaInventoryLevelUsageSensor'))
# @@protoc_insertion_point(module_scope)
