# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_capabilities/V3AlexaTimeHoldController.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3DateTime_pb2 as v3avs__types_dot_V3DateTime__pb2
from v3avs_types import V3Duration_pb2 as v3avs__types_dot_V3Duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_capabilities/V3AlexaTimeHoldController.proto',
  package='v3avs_capabilities',
  syntax='proto3',
  serialized_pb=_b('\n2v3avs_capabilities/V3AlexaTimeHoldController.proto\x12\x12v3avs_capabilities\x1a\x1cv3avs_types/V3DateTime.proto\x1a\x1cv3avs_types/V3Duration.proto\"\x8d\x05\n\x19V3AlexaTimeHoldController\x1a\xf7\x01\n\tDirective\x12S\n\x0e\x64irective_name\x18\x01 \x01(\x0e\x32;.v3avs_capabilities.V3AlexaTimeHoldController.DirectiveName\x12\x42\n\x04hold\x18\x02 \x01(\x0b\x32\x32.v3avs_capabilities.V3AlexaTimeHoldController.HoldH\x00\x12\x46\n\x06resume\x18\x03 \x01(\x0b\x32\x34.v3avs_capabilities.V3AlexaTimeHoldController.ResumeH\x00\x42\t\n\x07payload\x1a\x07\n\x05\x45vent\x1ah\n\x04Hold\x12\x30\n\x0fhold_start_time\x18\x01 \x01(\x0b\x32\x17.v3avs_types.V3DateTime\x12.\n\rhold_duration\x18\x02 \x01(\x0b\x32\x17.v3avs_types.V3Duration\x1a\x08\n\x06Resume\x1aI\n\x15HoldStartTimeProperty\x12\x30\n\x0fhold_start_time\x18\x01 \x01(\x0b\x32\x17.v3avs_types.V3DateTime\x1a\x45\n\x13HoldEndTimeProperty\x12.\n\rhold_end_time\x18\x01 \x01(\x0b\x32\x17.v3avs_types.V3DateTime\"%\n\rDirectiveName\x12\x08\n\x04HOLD\x10\x00\x12\n\n\x06RESUME\x10\x01\"@\n\x0cPropertyName\x12\x18\n\x14HOLD_START_TIME_PROP\x10\x00\x12\x16\n\x12HOLD_END_TIME_PROP\x10\x01\x42\x45\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\x17\x41lexaTimeHoldControllerb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3DateTime__pb2.DESCRIPTOR,v3avs__types_dot_V3Duration__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVENAME = _descriptor.EnumDescriptor(
  name='DirectiveName',
  full_name='v3avs_capabilities.V3AlexaTimeHoldController.DirectiveName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HOLD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESUME', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=685,
  serialized_end=722,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVENAME)

_V3ALEXATIMEHOLDCONTROLLER_PROPERTYNAME = _descriptor.EnumDescriptor(
  name='PropertyName',
  full_name='v3avs_capabilities.V3AlexaTimeHoldController.PropertyName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HOLD_START_TIME_PROP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOLD_END_TIME_PROP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=724,
  serialized_end=788,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXATIMEHOLDCONTROLLER_PROPERTYNAME)


_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE = _descriptor.Descriptor(
  name='Directive',
  full_name='v3avs_capabilities.V3AlexaTimeHoldController.Directive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='directive_name', full_name='v3avs_capabilities.V3AlexaTimeHoldController.Directive.directive_name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hold', full_name='v3avs_capabilities.V3AlexaTimeHoldController.Directive.hold', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resume', full_name='v3avs_capabilities.V3AlexaTimeHoldController.Directive.resume', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='v3avs_capabilities.V3AlexaTimeHoldController.Directive.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=165,
  serialized_end=412,
)

_V3ALEXATIMEHOLDCONTROLLER_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='v3avs_capabilities.V3AlexaTimeHoldController.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=421,
)

_V3ALEXATIMEHOLDCONTROLLER_HOLD = _descriptor.Descriptor(
  name='Hold',
  full_name='v3avs_capabilities.V3AlexaTimeHoldController.Hold',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hold_start_time', full_name='v3avs_capabilities.V3AlexaTimeHoldController.Hold.hold_start_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hold_duration', full_name='v3avs_capabilities.V3AlexaTimeHoldController.Hold.hold_duration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=527,
)

_V3ALEXATIMEHOLDCONTROLLER_RESUME = _descriptor.Descriptor(
  name='Resume',
  full_name='v3avs_capabilities.V3AlexaTimeHoldController.Resume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=537,
)

_V3ALEXATIMEHOLDCONTROLLER_HOLDSTARTTIMEPROPERTY = _descriptor.Descriptor(
  name='HoldStartTimeProperty',
  full_name='v3avs_capabilities.V3AlexaTimeHoldController.HoldStartTimeProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hold_start_time', full_name='v3avs_capabilities.V3AlexaTimeHoldController.HoldStartTimeProperty.hold_start_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=612,
)

_V3ALEXATIMEHOLDCONTROLLER_HOLDENDTIMEPROPERTY = _descriptor.Descriptor(
  name='HoldEndTimeProperty',
  full_name='v3avs_capabilities.V3AlexaTimeHoldController.HoldEndTimeProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hold_end_time', full_name='v3avs_capabilities.V3AlexaTimeHoldController.HoldEndTimeProperty.hold_end_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=683,
)

_V3ALEXATIMEHOLDCONTROLLER = _descriptor.Descriptor(
  name='V3AlexaTimeHoldController',
  full_name='v3avs_capabilities.V3AlexaTimeHoldController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE, _V3ALEXATIMEHOLDCONTROLLER_EVENT, _V3ALEXATIMEHOLDCONTROLLER_HOLD, _V3ALEXATIMEHOLDCONTROLLER_RESUME, _V3ALEXATIMEHOLDCONTROLLER_HOLDSTARTTIMEPROPERTY, _V3ALEXATIMEHOLDCONTROLLER_HOLDENDTIMEPROPERTY, ],
  enum_types=[
    _V3ALEXATIMEHOLDCONTROLLER_DIRECTIVENAME,
    _V3ALEXATIMEHOLDCONTROLLER_PROPERTYNAME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=788,
)

_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.fields_by_name['directive_name'].enum_type = _V3ALEXATIMEHOLDCONTROLLER_DIRECTIVENAME
_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.fields_by_name['hold'].message_type = _V3ALEXATIMEHOLDCONTROLLER_HOLD
_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.fields_by_name['resume'].message_type = _V3ALEXATIMEHOLDCONTROLLER_RESUME
_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.containing_type = _V3ALEXATIMEHOLDCONTROLLER
_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.oneofs_by_name['payload'].fields.append(
  _V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.fields_by_name['hold'])
_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.fields_by_name['hold'].containing_oneof = _V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.oneofs_by_name['payload']
_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.oneofs_by_name['payload'].fields.append(
  _V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.fields_by_name['resume'])
_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.fields_by_name['resume'].containing_oneof = _V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE.oneofs_by_name['payload']
_V3ALEXATIMEHOLDCONTROLLER_EVENT.containing_type = _V3ALEXATIMEHOLDCONTROLLER
_V3ALEXATIMEHOLDCONTROLLER_HOLD.fields_by_name['hold_start_time'].message_type = v3avs__types_dot_V3DateTime__pb2._V3DATETIME
_V3ALEXATIMEHOLDCONTROLLER_HOLD.fields_by_name['hold_duration'].message_type = v3avs__types_dot_V3Duration__pb2._V3DURATION
_V3ALEXATIMEHOLDCONTROLLER_HOLD.containing_type = _V3ALEXATIMEHOLDCONTROLLER
_V3ALEXATIMEHOLDCONTROLLER_RESUME.containing_type = _V3ALEXATIMEHOLDCONTROLLER
_V3ALEXATIMEHOLDCONTROLLER_HOLDSTARTTIMEPROPERTY.fields_by_name['hold_start_time'].message_type = v3avs__types_dot_V3DateTime__pb2._V3DATETIME
_V3ALEXATIMEHOLDCONTROLLER_HOLDSTARTTIMEPROPERTY.containing_type = _V3ALEXATIMEHOLDCONTROLLER
_V3ALEXATIMEHOLDCONTROLLER_HOLDENDTIMEPROPERTY.fields_by_name['hold_end_time'].message_type = v3avs__types_dot_V3DateTime__pb2._V3DATETIME
_V3ALEXATIMEHOLDCONTROLLER_HOLDENDTIMEPROPERTY.containing_type = _V3ALEXATIMEHOLDCONTROLLER
_V3ALEXATIMEHOLDCONTROLLER_DIRECTIVENAME.containing_type = _V3ALEXATIMEHOLDCONTROLLER
_V3ALEXATIMEHOLDCONTROLLER_PROPERTYNAME.containing_type = _V3ALEXATIMEHOLDCONTROLLER
DESCRIPTOR.message_types_by_name['V3AlexaTimeHoldController'] = _V3ALEXATIMEHOLDCONTROLLER

V3AlexaTimeHoldController = _reflection.GeneratedProtocolMessageType('V3AlexaTimeHoldController', (_message.Message,), dict(

  Directive = _reflection.GeneratedProtocolMessageType('Directive', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXATIMEHOLDCONTROLLER_DIRECTIVE,
    __module__ = 'v3avs_capabilities.V3AlexaTimeHoldController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaTimeHoldController.Directive)
    ))
  ,

  Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXATIMEHOLDCONTROLLER_EVENT,
    __module__ = 'v3avs_capabilities.V3AlexaTimeHoldController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaTimeHoldController.Event)
    ))
  ,

  Hold = _reflection.GeneratedProtocolMessageType('Hold', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXATIMEHOLDCONTROLLER_HOLD,
    __module__ = 'v3avs_capabilities.V3AlexaTimeHoldController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaTimeHoldController.Hold)
    ))
  ,

  Resume = _reflection.GeneratedProtocolMessageType('Resume', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXATIMEHOLDCONTROLLER_RESUME,
    __module__ = 'v3avs_capabilities.V3AlexaTimeHoldController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaTimeHoldController.Resume)
    ))
  ,

  HoldStartTimeProperty = _reflection.GeneratedProtocolMessageType('HoldStartTimeProperty', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXATIMEHOLDCONTROLLER_HOLDSTARTTIMEPROPERTY,
    __module__ = 'v3avs_capabilities.V3AlexaTimeHoldController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaTimeHoldController.HoldStartTimeProperty)
    ))
  ,

  HoldEndTimeProperty = _reflection.GeneratedProtocolMessageType('HoldEndTimeProperty', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXATIMEHOLDCONTROLLER_HOLDENDTIMEPROPERTY,
    __module__ = 'v3avs_capabilities.V3AlexaTimeHoldController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaTimeHoldController.HoldEndTimeProperty)
    ))
  ,
  DESCRIPTOR = _V3ALEXATIMEHOLDCONTROLLER,
  __module__ = 'v3avs_capabilities.V3AlexaTimeHoldController_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaTimeHoldController)
  ))
_sym_db.RegisterMessage(V3AlexaTimeHoldController)
_sym_db.RegisterMessage(V3AlexaTimeHoldController.Directive)
_sym_db.RegisterMessage(V3AlexaTimeHoldController.Event)
_sym_db.RegisterMessage(V3AlexaTimeHoldController.Hold)
_sym_db.RegisterMessage(V3AlexaTimeHoldController.Resume)
_sym_db.RegisterMessage(V3AlexaTimeHoldController.HoldStartTimeProperty)
_sym_db.RegisterMessage(V3AlexaTimeHoldController.HoldEndTimeProperty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\027AlexaTimeHoldController'))
# @@protoc_insertion_point(module_scope)
