configName: samd21_cnano
folderName: ''
format_version: v1.0
frameworkPath: ../../../../Harmony_public_release
processor: ATSAMD21G17D
projectName: ''
settings:
  PackageFilter: audio;bsp;bt;core;csp;gfx;gfx_apps;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.104\samd21d\atdf\ATSAMD21G17D.atdf
