format_version: v1.0
configName: sam_e54_xpro
folderName: ftp_client_sam_e54_xpro
frameworkPath: D:\MPLABX_IDE\MCC_Harmony_path
processor: ATSAME54P20A
projectName: ftp_client_sam_e54_xpro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME54_DFP\3.7.122\atdf\ATSAME54P20A.atdf
