format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_i2c}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: DRV_I2C_ASYNC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: DRV_I2C_ASYNC_SRC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: DRV_I2C_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_i2c, value: Synchronous}
  - type: File
    attributes: {id: DRV_I2C_SYNC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: DRV_I2C_SYNC_SRC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_i2c}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: DRV_I2C_NUM_CLIENTS}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '2'}
      - type: String
        attributes: {id: DRV_I2C_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_i2c_0, value: SERCOM2}
      - type: Integer
        attributes: {id: DRV_I2C_QUEUE_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_i2c_I2C_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: sercom2}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SERCOM2_I2C}
- type: ElementPosition
  attributes: {x: '158', y: '174', id: drv_i2c}
