format_version: v1.0
type: UniqueComponent
attributes: {id: supc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SUPC_VREG_LPEFF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '30', y: '220', id: supc}
