configName: pic32cxsg61_cultra_can_host
folderName: pic32cx_sg61_secure_can_host
format_version: v1.0
frameworkPath: D:\MCC_Repo
processor: PIC32CX1025SG61128
projectName: pic32cx_sg61_secure_can_host
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CX-SG61_DFP\1.1.122
