package:
  format-version: "1.0.0"
  name: "reference_apps"
  version: "dev"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.16.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.16.0"
    - name: "core"
      type: "package"
      version: "v3.12.0"
    - name: "bsp"
      type: "package"
      version: "v3.15.0"      
    - name: "usb"
      type: "package"
      version: "v3.11.0-E2"       
    - name: "audio"
      type: "package"
      version: "v3.6.0"  
    - name: "gfx"
      type: "package"
      version: "v3.12.2"  
    - name: "touch"
      type: "package"
      version: "v3.13.1"  
    - name: "net"
      type: "package"
      version: "v3.9.1"  
    - name: "wireless_wifi"
      type: "package"
      version: "v3.8.0"        
    - name: "bt"
      type: "package"
      version: "v3.4.1"  
    - name: "bootloader"
      type: "package"
      version: "v3.6.0"  
    - name: "bootloader_apps_uart"
      type: "package"
      version: "v3.2.0"  
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.4.6"  
    - name: "wolfssl"
      type: "package"
      version: "v4.7.0"  
    - name: "crypto"
      type: "package"
      version: "v3.7.6"  
    - name: "aws_cloud"
      type: "package"
      version: "v3.2.0"  
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.5.1"        