package:
  format-version: "1.0.0"
  name: "reference_apps"
  version: "dev"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.18.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.18.0"
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "bsp"
      type: "package"
      version: "v3.17.0"
    - name: "usb"
      type: "package"
      version: "v3.11.0-E2"
    - name: "audio"
      type: "package"
      version: "v3.6.0"
    - name: "gfx"
      type: "package"
      version: "v3.13.0"
    - name: "touch"
      type: "package"
      version: "v3.14.0"
    - name: "net"
      type: "package"
      version: "v3.10.1"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.9.0"
    - name: "bt"
      type: "package"
      version: "v3.4.1"
    - name: "bootloader"
      type: "package"
      version: "v3.6.0"
    - name: "bootloader_apps_uart"
      type: "package"
      version: "v3.2.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.0"
    - name: "aws_cloud"
      type: "package"
      version: "v3.2.0"
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.5.1"