format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32CM_LS60_Curiosity_Pro, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '0', y: '358', id: BSP_PIC32CM_LS60_Curiosity_Pro}
