format_version: v1.0
configName: pic32cm_ls60_cpro
folderName: pic32cm_ls60_cpro_NonSecure
frameworkPath: C:\gitHub
processor: PIC32CM5164LS60100
projectName: pic32cm_ls60_cpro_NonSecure
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'true'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-LS_DFP\1.1.162\PIC32CM-LS60\atdf\PIC32CM5164LS60100.atdf
