format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_sdmmc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DRV_SDMMC_COMMON_FS_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sdmmc, value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_sdmmc}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: DRV_SDMMC_BUFFER_OBJECT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: '1'}
      - type: Combo
        attributes: {id: DRV_SDMMC_BUS_SPEED}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: HIGH_SPEED}
      - type: String
        attributes: {id: DRV_SDMMC_CARD_DETECTION_METHOD}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: Use SDCD Pin}
      - type: Boolean
        attributes: {id: DRV_SDMMC_FS_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: 'true'}
      - type: String
        attributes: {id: DRV_SDMMC_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: SDHC}
      - type: Boolean
        attributes: {id: DRV_SDMMC_PLIB_SDCD_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_SDMMC_PLIB_SDWP_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: 'false'}
      - type: Menu
        attributes: {id: DRV_SDMMC_RTOS_MENU}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: DRV_SDMMC_SYS_RTOS_TASK}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: Combo
        attributes: {id: DRV_SDMMC_TRANSFER_BUS_WIDTH}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: 4-bit}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_sdmmc_SDHC_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: sdhc}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SDHC_SDHC}
- type: ElementPosition
  attributes: {x: '849', y: '248', id: drv_sdmmc}
