format_version: v1.0
type: UniqueComponent
attributes: {id: drv_usbhs_v1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: ENABLE_DRV_USB_DEVICE_SOURCE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbhs_v1, value: 'false'}
  - type: Boolean
    attributes: {id: ENABLE_DRV_USB_HOST_SOURCE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbhs_v1, value: 'true'}
  - type: Combo
    attributes: {id: USB_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbhs_v1, value: Host}
- type: ElementPosition
  attributes: {x: '552', y: '12', id: drv_usbhs_v1}
