format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_i2c}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_I2C_FORCED_WRITE_API_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_i2c, value: '0'}
  - type: Combo
    attributes: {id: DRV_I2C_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_i2c, value: Asynchronous}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_i2c}
    children:
    - type: Symbols
      children:
      - type: Boolean
        attributes: {id: DRV_I2C_INCLUDE_FORCED_WRITE_API}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_i2c_0, value: 'false'}
      - type: String
        attributes: {id: DRV_I2C_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_i2c_0, value: I2C2}
      - type: Integer
        attributes: {id: DRV_I2C_QUEUE_SIZE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '50'}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: drv_i2c}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: gfx_maxtouch_controller}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: i2c}
      - type: DirectDependency
        attributes: {id: drv_i2c_I2C_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: i2c2}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: I2C2_I2C}
  - type: InstanceComponent
    attributes: {instance: '1', id: drv_i2c}
    children:
    - type: Symbols
      children:
      - type: Boolean
        attributes: {id: DRV_I2C_INCLUDE_FORCED_WRITE_API}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_i2c_1, value: 'false'}
      - type: String
        attributes: {id: DRV_I2C_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_i2c_1, value: I2C1}
      - type: Integer
        attributes: {id: DRV_I2C_QUEUE_SIZE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '50'}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: drv_i2c}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: audio_codec_ak4954}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: DRV_I2C}
      - type: DirectDependency
        attributes: {id: drv_i2c_I2C_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: i2c1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: I2C1_I2C}
- type: ElementPosition
  attributes: {x: '202', y: '78', id: drv_i2c}
