format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_disp_pdatm4301b_480x272}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: gfx_display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_glcd}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: Graphics Display}
  - type: DirectCapability
    attributes: {id: touch_panel}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_maxtouch_controller}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: touch_panel}
- type: ElementPosition
  attributes: {x: '539', y: '95', id: gfx_disp_pdatm4301b_480x272}
