format_version: v1.0
type: UniqueComponent
attributes: {id: usb_host_msd}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: USB Host MSD}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_fs}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_fs_DRV_MEDIA_dependency}
- type: ElementPosition
  attributes: {x: '774', y: '434', id: usb_host_msd}
