format_version: v1.0
configName: pic32cz_ca90_cult
folderName: pic32cz_ca90_cult
frameworkPath: C:\h_v3
processor: PIC32CZ8110CA90208
projectName: pic32cz_ca90_cult
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CZ-CA90_DFP\1.0.18\CA90\atdf\PIC32CZ8110CA90208.atdf
