format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MZ_DA_Radial_Board, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '660', y: '20', id: BSP_PIC32MZ_DA_Radial_Board}
