format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_disp_generic}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BacklightDisable}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '0'}
  - type: Integer
    attributes: {id: BacklightEnable}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '1'}
  - type: Boolean
    attributes: {id: ChipSelectPolarity}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: 'true'}
  - type: Boolean
    attributes: {id: DataEnable}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: 'true'}
  - type: Boolean
    attributes: {id: DataEnablePolarity}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: 'true'}
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '432'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '432'}
  - type: Boolean
    attributes: {id: HSYNCNegative}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: 'false'}
  - type: Integer
    attributes: {id: HorzBackPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '5'}
  - type: Integer
    attributes: {id: HorzFrontPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '5'}
  - type: Integer
    attributes: {id: HorzPulseWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '5'}
  - type: Boolean
    attributes: {id: ResetPolarity}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: 'true'}
  - type: Boolean
    attributes: {id: UseChipSelect}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: 'true'}
  - type: Boolean
    attributes: {id: UseReset}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: 'true'}
  - type: Boolean
    attributes: {id: VSYNCNegative}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: 'false'}
  - type: Integer
    attributes: {id: VertBackPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '5'}
  - type: Integer
    attributes: {id: VertFrontPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '5'}
  - type: Integer
    attributes: {id: VertPulseWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_disp_generic, value: '5'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: gfx_display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_glcd}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: Graphics Display}
  - type: DirectCapability
    attributes: {id: touch_panel}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_generic_touch_controller}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: touch_panel}
- type: ElementPosition
  attributes: {x: '90', y: '239', id: gfx_disp_generic}
