format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_driver_2dgpu}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: gfx_driver_2dgpu}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_legato}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gpu_driver}
- type: ElementPosition
  attributes: {x: '458', y: '413', id: le_gfx_driver_2dgpu}
