format_version: v1.0
configName: pic32cm_jh01_cnano
folderName: pic32cm_jh01_cnano
frameworkPath: C:\h3
processor: PIC32CM5164JH01048
projectName: pic32cm_jh01_cnano
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-JH_DFP\1.0.88\PIC32CM-JH01\atdf\PIC32CM5164JH01048.atdf
