configName: sam_e51_cnano
folderName: sam_e51_cnano
format_version: v1.0
frameworkPath: D:\Projects\git_hub
processor: ATSAME51J20A
projectName: sam_e51_cnano
settings:
  PackageFilter: audio;bsp;bt;core;crypto;cryptoauthlib;csp;csp_apps_sam_d5x_e5x;Devices;dev_packs;gfx;gfx_apps;harmony-services;micrium_ucos3;net;quick_docs;reference_apps;tflm;touch;usb;wireless_apps_winc1500;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME51_DFP\3.5.104\atdf\ATSAME51J20A.atdf
