format_version: v1.0
configName: lcdc_rgba8888_mxt_9x60_wvga
folderName: Quickstart_sam_9x60_cu
frameworkPath: C:\Users\i70650\har3
processor: SAM9X60D1G
projectName: Quickstart_sam_9x60_cu
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAM9X60_DFP\1.7.85\atdf\SAM9X60D1G.atdf
