configName: sam_e51_cnano
folderName: sam_e51_cnano
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME51J20A
projectName: getting_started_with_legato_graphics_sam_e51_cnano
settings:
  PackageFilter: audio;bsp;bt;core;crypto;cryptoauthlib;csp;gfx;gfx_apps;reference_apps;usb;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME51_DFP\3.4.98\atdf\ATSAME51J20A.atdf
