format_version: v1.0
type: UniqueComponent
attributes: {id: usart1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BAUD_RATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '115200'}
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart1, value: '81'}
  - type: Comment
    attributes: {id: USART_BAUD_WARNING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: USART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart1, value: '150000000'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart1, value: 'true'}
  - type: KeyValueSet
    attributes: {id: USART_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart1, value: '0'}
  - type: Comment
    attributes: {id: USART_NVIC_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: USART_RING_BUFFER_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart1, value: 'false'}
  - type: Integer
    attributes: {id: USART_SPI_BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart1, value: '150'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: USART1_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_usart_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_usart_UART_dependency}
- type: ElementPosition
  attributes: {x: '198', y: '93', id: usart1}
