format_version: v1.0
configName: pic32cm_mc00_curiosity_pro
folderName: pic32cm_mc00_curiosity_pro
frameworkPath: C:\gitHub
processor: PIC32CM1216MC00048
projectName: pic32cm_mc00_curiosity_pro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-MC_DFP\1.3.58\PIC32CM1216MC00048\atdf\PIC32CM1216MC00048.atdf
