configName: pic32cm_mc00_cnano
folderName: pic32cm_mc00_cnano
format_version: v1.0
frameworkPath: ..\..
processor: PIC32CM1216MC00032
projectName: rapid_prototype_event3_ext1_pic32cm_mc00_cnano
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;bt;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;csp_apps_pic32cm_mc00;csp_apps_sam_c20_c21;csp_apps_sam_d21_da1;dev_packs;gfx;gfx_apps;gfx_apps_sam_d5x_e5x;net;net_apps_sam_e70_v71;quick_docs;reference_apps;touch;usb;wireless_apps_winc1500;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-MC_DFP\1.3.58\PIC32CM1216MC00032\atdf\PIC32CM1216MC00032.atdf
