format_version: v1.0
configName: pic32cm_mc00_cnano
folderName: pic32cm_mc00_cnano
frameworkPath: D:\LTBD\Harmony_public_release
processor: PIC32CM1216MC00032
projectName: pic32cm_mc00_cnano
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-MC_DFP\1.3.58\PIC32CM1216MC00032\atdf\PIC32CM1216MC00032.atdf
