format_version: v1.0
type: GroupComponent
attributes: {displayName: PRESENTATION LAYER, id: PRESENTATION LAYER}
children:
- type: ElementPosition
  attributes: {x: '370', y: '120', id: PRESENTATION LAYER}
- type: Attachments
  children:
  - type: Attachment
    attributes: {targetComponentID: TCP/IP STACK, namespace: net_Pres, id: Net_Pres_Crypto_Dependency,
      targetAttachmentID: 'TCP/IP STACK:net_Pres:Net_Pres_Crypto_Dependency'}
