format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipSntp}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_NTP_DEFAULT_IF}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipSntp, value: GMAC}
  - type: String
    attributes: {id: TCPIP_NTP_SERVER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: pool.ntp.org}
- type: ElementPosition
  attributes: {x: '190', y: '140', id: tcpipSntp}
