format_version: v1.0
configName: sam_l21_xpro
folderName: sam_l21_xpro
frameworkPath: D:\LTBD\Harmony_public_release
processor: ATSAML21J18B
projectName: sam_l21_xpro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAML21_DFP\3.5.87\saml21b\atdf\ATSAML21J18B.atdf
