format_version: v1.0
type: UniqueComponent
attributes: {id: supc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: SUPC_BBPS_CONF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: SUPC_VREG_LPEFF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SUPC_VREG_SEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '719', y: '192', id: supc}
