<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Microchip Wi-Fi RGB Easy Configuration Demo</title>
    <link href="/mchp.css" rel="stylesheet" type="text/css" />
    <script src="/mchp.js" type="text/javascript"></script>
</head>

<body onload="newAJAXCommand('status.xml');">

<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 65px 5px"><img src="/images/mchp.gif" alt="Microchip" align="left"/><img src="/images/harmony.gif" alt="Harmony" align="right"/></div>

<div id="title"><div class="right">Easy Configuration Demo Application</div><span id="hello">&nbsp;</span></div>

<div id="menu">
    <a href="/index.htm">Overview</a>
    <a href="/configure.htm">Network Configuration</a>
</div>
