format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_intf_spi4}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_INTERFACE_SPI_INDEX}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: DRV_SPI}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_spi_1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_spi}
  - type: DirectCapability
    attributes: {id: le_gfx_intf_spi4}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_external}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SPI Display Interface}
- type: ElementPosition
  attributes: {x: '780', y: '20', id: le_gfx_intf_spi4}
