# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3Count.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3Count.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x19v3avs_types/V3Count.proto\x12\x0bv3avs_types\"\xdf\x01\n\x07V3Count\x12\r\n\x05value\x18\x01 \x01(\x02\x12\'\n\x04size\x18\x02 \x01(\x0e\x32\x19.v3avs_types.V3Count.Size\"\x9b\x01\n\x04Size\x12\x15\n\x11\x45XTRA_EXTRA_LARGE\x10\x00\x12\t\n\x05JUMBO\x10\x01\x12\x0f\n\x0b\x45XTRA_LARGE\x10\x02\x12\t\n\x05LARGE\x10\x03\x12\n\n\x06MEDIUM\x10\x04\x12\t\n\x05SMALL\x10\x05\x12\x0f\n\x0b\x45XTRA_SMALL\x10\x06\x12\x15\n\x11\x45XTRA_EXTRA_SMALL\x10\x07\x12\n\n\x06SIZE_A\x10\x08\x12\n\n\x06SIZE_B\x10\tB,\n#com.amazon.proto.avs.v3.v3avs_typesB\x05\x43ountb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3COUNT_SIZE = _descriptor.EnumDescriptor(
  name='Size',
  full_name='v3avs_types.V3Count.Size',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXTRA_EXTRA_LARGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JUMBO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTRA_LARGE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LARGE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SMALL', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTRA_SMALL', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTRA_EXTRA_SMALL', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIZE_A', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIZE_B', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=111,
  serialized_end=266,
)
_sym_db.RegisterEnumDescriptor(_V3COUNT_SIZE)


_V3COUNT = _descriptor.Descriptor(
  name='V3Count',
  full_name='v3avs_types.V3Count',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v3avs_types.V3Count.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='v3avs_types.V3Count.size', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _V3COUNT_SIZE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=266,
)

_V3COUNT.fields_by_name['size'].enum_type = _V3COUNT_SIZE
_V3COUNT_SIZE.containing_type = _V3COUNT
DESCRIPTOR.message_types_by_name['V3Count'] = _V3COUNT

V3Count = _reflection.GeneratedProtocolMessageType('V3Count', (_message.Message,), dict(
  DESCRIPTOR = _V3COUNT,
  __module__ = 'v3avs_types.V3Count_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3Count)
  ))
_sym_db.RegisterMessage(V3Count)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\005Count'))
# @@protoc_insertion_point(module_scope)
