# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3InventoryConsumed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3Level_pb2 as v3avs__types_dot_V3Level__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3InventoryConsumed.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n%v3avs_types/V3InventoryConsumed.proto\x12\x0bv3avs_types\x1a\x19v3avs_types/V3Level.proto\":\n\x13V3InventoryConsumed\x12#\n\x05usage\x18\x01 \x01(\x0b\x32\x14.v3avs_types.V3LevelB8\n#com.amazon.proto.avs.v3.v3avs_typesB\x11InventoryConsumedb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3Level__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_V3INVENTORYCONSUMED = _descriptor.Descriptor(
  name='V3InventoryConsumed',
  full_name='v3avs_types.V3InventoryConsumed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usage', full_name='v3avs_types.V3InventoryConsumed.usage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=139,
)

_V3INVENTORYCONSUMED.fields_by_name['usage'].message_type = v3avs__types_dot_V3Level__pb2._V3LEVEL
DESCRIPTOR.message_types_by_name['V3InventoryConsumed'] = _V3INVENTORYCONSUMED

V3InventoryConsumed = _reflection.GeneratedProtocolMessageType('V3InventoryConsumed', (_message.Message,), dict(
  DESCRIPTOR = _V3INVENTORYCONSUMED,
  __module__ = 'v3avs_types.V3InventoryConsumed_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3InventoryConsumed)
  ))
_sym_db.RegisterMessage(V3InventoryConsumed)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\021InventoryConsumed'))
# @@protoc_insertion_point(module_scope)
