# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3TimeInterval.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3DateTime_pb2 as v3avs__types_dot_V3DateTime__pb2
from v3avs_types import V3Duration_pb2 as v3avs__types_dot_V3Duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3TimeInterval.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n v3avs_types/V3TimeInterval.proto\x12\x0bv3avs_types\x1a\x1cv3avs_types/V3DateTime.proto\x1a\x1cv3avs_types/V3Duration.proto\"\x89\x01\n\x0eV3TimeInterval\x12&\n\x05start\x18\x01 \x01(\x0b\x32\x17.v3avs_types.V3DateTime\x12$\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x17.v3avs_types.V3DateTime\x12)\n\x08\x64uration\x18\x03 \x01(\x0b\x32\x17.v3avs_types.V3DurationB3\n#com.amazon.proto.avs.v3.v3avs_typesB\x0cTimeIntervalb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3DateTime__pb2.DESCRIPTOR,v3avs__types_dot_V3Duration__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_V3TIMEINTERVAL = _descriptor.Descriptor(
  name='V3TimeInterval',
  full_name='v3avs_types.V3TimeInterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='v3avs_types.V3TimeInterval.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='v3avs_types.V3TimeInterval.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='v3avs_types.V3TimeInterval.duration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=247,
)

_V3TIMEINTERVAL.fields_by_name['start'].message_type = v3avs__types_dot_V3DateTime__pb2._V3DATETIME
_V3TIMEINTERVAL.fields_by_name['end'].message_type = v3avs__types_dot_V3DateTime__pb2._V3DATETIME
_V3TIMEINTERVAL.fields_by_name['duration'].message_type = v3avs__types_dot_V3Duration__pb2._V3DURATION
DESCRIPTOR.message_types_by_name['V3TimeInterval'] = _V3TIMEINTERVAL

V3TimeInterval = _reflection.GeneratedProtocolMessageType('V3TimeInterval', (_message.Message,), dict(
  DESCRIPTOR = _V3TIMEINTERVAL,
  __module__ = 'v3avs_types.V3TimeInterval_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3TimeInterval)
  ))
_sym_db.RegisterMessage(V3TimeInterval)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\014TimeInterval'))
# @@protoc_insertion_point(module_scope)
