format_version: v1.0
configName: sam_e54_xpro
folderName: sam_e54_xpro
frameworkPath: C:\Dev\harmony3
processor: ATSAME54P20A
projectName: sam_e54_xpro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME54_DFP\3.6.95\atdf\ATSAME54P20A.atdf
