format_version: v1.0
type: UniqueComponent
attributes: {id: sys_fs}
children:
- type: Symbols
  children:
  - type: Menu
    attributes: {id: MEDIA_CONF_MENU0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: SYS_FS_AUTO_MOUNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: SYS_FS_CLIENT_NUMBER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_1_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda1}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_2_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda2}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_3_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda3}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_4_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda4}
  - type: Combo
    attributes: {id: SYS_FS_MEDIA_TYPE_DEFINE_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SYS_FS_MEDIA_TYPE_MSD}
  - type: Integer
    attributes: {id: SYS_FS_TOTAL_VOLUMES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: '1'}
  - type: Integer
    attributes: {id: SYS_FS_VOLUME_NUMBER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: sys_fs_DRV_MEDIA_dependency}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: usb_host_msd, targetAttachmentID: USB Host
            MSD}
- type: ElementPosition
  attributes: {x: '370', y: '360', id: sys_fs}
