configName: sam_e54_xpro
folderName: ''
format_version: v1.0
frameworkPath: C:\microchip\Harmony3-GitHub
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: audio;aws_cloud;bootloader;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_uart;bsp;bt;classb_sam_e5x_d5x;core;core_apps_sam_d21_da1;core_apps_sam_d5x_e5x;core_apps_sam_e70_s70_v70_v71;crypto;cryptoauthlib;crypto_apps_encrypt_decrypt;crypto_apps_large_hash;crypto_apps_speed_test;csp;csp_apps_sam_9x60;csp_apps_sam_c20_c21;csp_apps_sam_d20;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_g55;csp_apps_sam_l10_l11;csp_apps_sam_l21;ethercat;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;micrium_ucos3;reference_apps;net;net;net;net;quick_docs;touch;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.4.70\atdf\ATSAME54P20A.atdf
