files:
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config\sam_d21_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: E69C059DD5E5D5EFDE5BC33855E3342B
  logicalPath: config\sam_d21_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: A38C2BA64DB0ED4F16B9EC496AA3D356
- generatedChecksum: 0D620848A5E14AED7954D4CCE0FE8F0B
  logicalPath: config\sam_d21_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0D620848A5E14AED7954D4CCE0FE8F0B
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_d21_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 40A0C249F1D418FD68D652E395745304
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: AFDD3103D90D95B08869FB78E82C0447
  logicalPath: config\sam_d21_xpro\peripheral\ac
  name: plib_ac.c
  physicalPath: peripheral\ac
  security: NON_SECURE
  type: SOURCE
  userChecksum: AFDD3103D90D95B08869FB78E82C0447
- generatedChecksum: 27F61852DF37ED1728D9FA42C1D5232A
  logicalPath: config\sam_d21_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: 27F61852DF37ED1728D9FA42C1D5232A
- generatedChecksum: DE994665DF8D623F789E0FC0EA88DAD7
  logicalPath: config\sam_d21_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE994665DF8D623F789E0FC0EA88DAD7
- generatedChecksum: 58C7321CEA741BE6B079F163366C59D5
  logicalPath: config\sam_d21_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 58C7321CEA741BE6B079F163366C59D5
- generatedChecksum: 12BB5180FB5A5EF3F5A1310030E4E6C5
  logicalPath: config\sam_d21_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: 12BB5180FB5A5EF3F5A1310030E4E6C5
- generatedChecksum: C1D48DE579F7240972E0DC85B80619EF
  logicalPath: config\sam_d21_xpro\peripheral\pm
  name: plib_pm.c
  physicalPath: peripheral\pm
  security: NON_SECURE
  type: SOURCE
  userChecksum: C1D48DE579F7240972E0DC85B80619EF
- generatedChecksum: 3D11E29BDE6ED557223369B602A2EE8B
  logicalPath: config\sam_d21_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3D11E29BDE6ED557223369B602A2EE8B
- generatedChecksum: 6B10AE37F86BD72299A1F344A1B57BED
  logicalPath: config\sam_d21_xpro\peripheral\rtc
  name: plib_rtc_timer.c
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6B10AE37F86BD72299A1F344A1B57BED
- generatedChecksum: 657CDDE80BEBAD774BEAA083344C4312
  logicalPath: config\sam_d21_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 657CDDE80BEBAD774BEAA083344C4312
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config\sam_d21_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: 78DE9319870227DC2FF47B9428D45405
  logicalPath: config\sam_d21_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 78DE9319870227DC2FF47B9428D45405
- generatedChecksum: E83A2568EB70A3E393A9421C4CEDDDD5
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E83A2568EB70A3E393A9421C4CEDDDD5
- generatedChecksum: 590A4F4CE794B1EB4CDE657634C91913
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 590A4F4CE794B1EB4CDE657634C91913
- generatedChecksum: D03E3BB47A437765D48AB851735F684D
  logicalPath: packs\ATSAMD21J18A_DFP
  name: atsamd21j18a.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: D03E3BB47A437765D48AB851735F684D
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: 016B5B4A71E106E734B16CA1517FF382
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 016B5B4A71E106E734B16CA1517FF382
- generatedChecksum: F33701DC755C896DA907CEF50AE3288A
  logicalPath: config\sam_d21_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F33701DC755C896DA907CEF50AE3288A
- generatedChecksum: A62880149571045CACABCBB3AC375EAD
  logicalPath: config\sam_d21_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: A62880149571045CACABCBB3AC375EAD
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_d21_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: C2E075A57123D0F17F6743EB79FB5708
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C2E075A57123D0F17F6743EB79FB5708
- generatedChecksum: 817445C5CD46BF44AEA791F24FFCFD9B
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 817445C5CD46BF44AEA791F24FFCFD9B
- generatedChecksum: D354D94F76074F550A3D39339988740E
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D354D94F76074F550A3D39339988740E
- generatedChecksum: CCEBBAD0032227AD71BE82D0A235ADD8
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CCEBBAD0032227AD71BE82D0A235ADD8
- generatedChecksum: 1F81BE55AB45CB807013941A75AA1A57
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1F81BE55AB45CB807013941A75AA1A57
- generatedChecksum: 56D435F7656CC2343B84F1E66D164D64
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: hmatrixb.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 56D435F7656CC2343B84F1E66D164D64
- generatedChecksum: 998DBA248933E5682F2276B60B8FD8D8
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: i2s.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 998DBA248933E5682F2276B60B8FD8D8
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: F37178E00FC83646B507901642A0100D
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F37178E00FC83646B507901642A0100D
- generatedChecksum: 7296DA017FF9C40DCC08191D6999B77B
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7296DA017FF9C40DCC08191D6999B77B
- generatedChecksum: D5A9C90744DEFF4CCDD467B77B6406CB
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D5A9C90744DEFF4CCDD467B77B6406CB
- generatedChecksum: E3C263FBBEEB289B3B37DA328B771CB2
  logicalPath: config\sam_d21_xpro\peripheral\ac
  name: plib_ac.h
  physicalPath: peripheral\ac
  security: NON_SECURE
  type: HEADER
  userChecksum: E3C263FBBEEB289B3B37DA328B771CB2
- generatedChecksum: C591D09F115E12D00921D14939E3900D
  logicalPath: config\sam_d21_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: C591D09F115E12D00921D14939E3900D
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_d21_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_d21_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: 71D16914F1E580B0AF77141622DCD865
  logicalPath: config\sam_d21_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 71D16914F1E580B0AF77141622DCD865
- generatedChecksum: AB789E6A8030C3A15707047A380F5B47
  logicalPath: config\sam_d21_xpro\peripheral\pm
  name: plib_pm.h
  physicalPath: peripheral\pm
  security: NON_SECURE
  type: HEADER
  userChecksum: AB789E6A8030C3A15707047A380F5B47
- generatedChecksum: 441A81023E29565763BA854026E1F6F4
  logicalPath: config\sam_d21_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 441A81023E29565763BA854026E1F6F4
- generatedChecksum: 1F343430456E04C6169D453BD52D3F39
  logicalPath: config\sam_d21_xpro\peripheral\rtc
  name: plib_rtc.h
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: HEADER
  userChecksum: 1F343430456E04C6169D453BD52D3F39
- generatedChecksum: DCC0369AFDD597FB63203FB1B7488E8B
  logicalPath: config\sam_d21_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: DCC0369AFDD597FB63203FB1B7488E8B
- generatedChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
  logicalPath: config\sam_d21_xpro\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
- generatedChecksum: EBC9AD17B5DCF76A8EDA531E3D2ECDA5
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EBC9AD17B5DCF76A8EDA531E3D2ECDA5
- generatedChecksum: 7AED24682E6782ACD411A220C99C4F7A
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7AED24682E6782ACD411A220C99C4F7A
- generatedChecksum: B838D9B01315613C8EFF25C5BB950F80
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B838D9B01315613C8EFF25C5BB950F80
- generatedChecksum: 87D1C55E9ECF3BCCB24FA600CBFCC930
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 87D1C55E9ECF3BCCB24FA600CBFCC930
- generatedChecksum: C5D1633B6BB74A69DB0CBA77291BC43C
  logicalPath: packs\ATSAMD21J18A_DFP\pio
  name: samd21j18a.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: C5D1633B6BB74A69DB0CBA77291BC43C
- generatedChecksum: 4253FCE0B35C0AB2AA0253652C488761
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4253FCE0B35C0AB2AA0253652C488761
- generatedChecksum: 0258BE6535CDDE44682CC0CDCB222880
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0258BE6535CDDE44682CC0CDCB222880
- generatedChecksum: E9BCB2B0F7AA6142C2681C1155F88131
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E9BCB2B0F7AA6142C2681C1155F88131
- generatedChecksum: 5819925250D9C7C86B56A48BF0949196
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5819925250D9C7C86B56A48BF0949196
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_d21_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: F123D6104DB9C55CD684CE27F3B22781
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: usb.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F123D6104DB9C55CD684CE27F3B22781
- generatedChecksum: AF14D78B734053187B6E93E19BD70449
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AF14D78B734053187B6E93E19BD70449
- generatedChecksum: D5CD9172C8EF08FDC00E4F569329FFCF
  logicalPath: config\sam_d21_xpro
  name: ATSAMD21J18A.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 9311D40BCB46694419846F81034D32FD
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d21_xpro;../src/packs/ATSAMD21J18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d21_xpro;../src/packs/ATSAMD21J18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
