format_version: v1.0
configName: sam_d21_cnano
folderName: atmega4809_to_samd21_migration
frameworkPath: C:\gitHub
processor: ATSAMD21G17D
projectName: atmega4809_to_samd21_migration
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMD21_DFP\3.4.116\samd21d\atdf\ATSAMD21G17D.atdf
