format_version: v1.0
configName: same51_barcode_scanner
folderName: same51_barcode_scanner
frameworkPath: D:\H3
processor: ATSAME51J20A
projectName: same51_barcode_scanner
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME51_DFP\3.7.242\atdf\ATSAME51J20A.atdf
