format_version: v1.0
configName: AWS_PKI_Cloud
folderName: cloud_connect_NonSecure
frameworkPath: C:\Dev\harmony3
processor: PIC32CM5164LS60100
projectName: cloud_connect_NonSecure
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'true'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-LS_DFP\1.1.162\PIC32CM-LS60\atdf\PIC32CM5164LS60100.atdf
