configName: pic32cxsg61_can_node
folderName: pic32cx_sg61_secure_can_node_bootloader
format_version: v1.0
frameworkPath: D:\MCC_Repo
processor: PIC32CX1025SG61128
projectName: pic32cx_sg61_secure_can_node_bootloader
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CX-SG61_DFP\1.1.122
