configName: pic32cx_sg61_cult
folderName: pic32cx_sg61_cult
format_version: v1.0
frameworkPath: D:\H3
processor: PIC32CX1025SG61128
projectName: pic32cx_sg61_cult
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CX-SG61_DFP\1.2.124
