format_version: v1.0
type: GroupComponent
attributes: {displayName: PRESENTATION LAYER, id: PRESENTATION LAYER}
children:
- type: ElementPosition
  attributes: {x: '230', y: '80', id: PRESENTATION LAYER}
- type: Attachments
  children:
  - type: Attachment
    attributes: {namespace: net_Pres, id: Net_Pres_Crypto_Dependency}
