format_version: v1.0
type: UniqueComponent
attributes: {id: afec1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ADC_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: AFEC1_CallbackRegister}
  - type: String
    attributes: {id: ADC_CH_PHASE_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: AFEC_CH0}
  - type: String
    attributes: {id: ADC_CH_PHASE_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: AFEC_CH6}
  - type: String
    attributes: {id: ADC_CH_POT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: AFEC_CH10}
  - type: String
    attributes: {id: ADC_CH_VDC_BUS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: AFEC_CH7}
  - type: String
    attributes: {id: ADC_GET_RESULT_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: AFEC1_ChannelResultGet}
  - type: String
    attributes: {id: ADC_IS_RESULT_READY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: AFEC1_ChannelResultIsReady}
  - type: String
    attributes: {id: ADC_START_CONV_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: AFEC1_ConversionStart}
  - type: Combo
    attributes: {id: AFEC_6_CGR_GAIN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: AFEC_6_CHER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: AFEC_6_COCR_AOFF}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: AFEC_6_IER_EOC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: AFEC_6_NAME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: AFEC_6_NEG_INP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: AFEC_6_POS_INP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: AFEC_CLK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: '6000000'}
  - type: Comment
    attributes: {id: AFEC_CLK_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: AFEC_CONV_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Comment
    attributes: {id: AFEC_CONV_TIME}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Conversion Time is 3.83333333333 us ****'}
  - type: Integer
    attributes: {id: AFEC_MR_PRESCAL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '24'}
  - type: String
    attributes: {id: INTERRUPT_ADC_RESULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: afec1, value: AFEC1_IRQn}
- type: ElementPosition
  attributes: {x: '21', y: '371', id: afec1}
