# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_capabilities/V3AlexaCookingTemperatureSensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3Temperature_pb2 as v3avs__types_dot_V3Temperature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_capabilities/V3AlexaCookingTemperatureSensor.proto',
  package='v3avs_capabilities',
  syntax='proto3',
  serialized_pb=_b('\n8v3avs_capabilities/V3AlexaCookingTemperatureSensor.proto\x12\x12v3avs_capabilities\x1a\x1fv3avs_types/V3Temperature.proto\"\xbc\x01\n\x1fV3AlexaCookingTemperatureSensor\x1a\x0b\n\tDirective\x1a\x07\n\x05\x45vent\x1aU\n\x1a\x43ookingTemperatureProperty\x12\x37\n\x13\x63ooking_temperature\x18\x01 \x01(\x0b\x32\x1a.v3avs_types.V3Temperature\",\n\x0cPropertyName\x12\x1c\n\x18\x43OOKING_TEMPERATURE_PROP\x10\x00\x42K\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\x1d\x41lexaCookingTemperatureSensorb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3Temperature__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ALEXACOOKINGTEMPERATURESENSOR_PROPERTYNAME = _descriptor.EnumDescriptor(
  name='PropertyName',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureSensor.PropertyName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COOKING_TEMPERATURE_PROP', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=258,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXACOOKINGTEMPERATURESENSOR_PROPERTYNAME)


_V3ALEXACOOKINGTEMPERATURESENSOR_DIRECTIVE = _descriptor.Descriptor(
  name='Directive',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureSensor.Directive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=160,
)

_V3ALEXACOOKINGTEMPERATURESENSOR_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureSensor.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=169,
)

_V3ALEXACOOKINGTEMPERATURESENSOR_COOKINGTEMPERATUREPROPERTY = _descriptor.Descriptor(
  name='CookingTemperatureProperty',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureSensor.CookingTemperatureProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cooking_temperature', full_name='v3avs_capabilities.V3AlexaCookingTemperatureSensor.CookingTemperatureProperty.cooking_temperature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=256,
)

_V3ALEXACOOKINGTEMPERATURESENSOR = _descriptor.Descriptor(
  name='V3AlexaCookingTemperatureSensor',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_V3ALEXACOOKINGTEMPERATURESENSOR_DIRECTIVE, _V3ALEXACOOKINGTEMPERATURESENSOR_EVENT, _V3ALEXACOOKINGTEMPERATURESENSOR_COOKINGTEMPERATUREPROPERTY, ],
  enum_types=[
    _V3ALEXACOOKINGTEMPERATURESENSOR_PROPERTYNAME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=302,
)

_V3ALEXACOOKINGTEMPERATURESENSOR_DIRECTIVE.containing_type = _V3ALEXACOOKINGTEMPERATURESENSOR
_V3ALEXACOOKINGTEMPERATURESENSOR_EVENT.containing_type = _V3ALEXACOOKINGTEMPERATURESENSOR
_V3ALEXACOOKINGTEMPERATURESENSOR_COOKINGTEMPERATUREPROPERTY.fields_by_name['cooking_temperature'].message_type = v3avs__types_dot_V3Temperature__pb2._V3TEMPERATURE
_V3ALEXACOOKINGTEMPERATURESENSOR_COOKINGTEMPERATUREPROPERTY.containing_type = _V3ALEXACOOKINGTEMPERATURESENSOR
_V3ALEXACOOKINGTEMPERATURESENSOR_PROPERTYNAME.containing_type = _V3ALEXACOOKINGTEMPERATURESENSOR
DESCRIPTOR.message_types_by_name['V3AlexaCookingTemperatureSensor'] = _V3ALEXACOOKINGTEMPERATURESENSOR

V3AlexaCookingTemperatureSensor = _reflection.GeneratedProtocolMessageType('V3AlexaCookingTemperatureSensor', (_message.Message,), dict(

  Directive = _reflection.GeneratedProtocolMessageType('Directive', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURESENSOR_DIRECTIVE,
    __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureSensor_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureSensor.Directive)
    ))
  ,

  Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURESENSOR_EVENT,
    __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureSensor_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureSensor.Event)
    ))
  ,

  CookingTemperatureProperty = _reflection.GeneratedProtocolMessageType('CookingTemperatureProperty', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURESENSOR_COOKINGTEMPERATUREPROPERTY,
    __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureSensor_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureSensor.CookingTemperatureProperty)
    ))
  ,
  DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURESENSOR,
  __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureSensor_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureSensor)
  ))
_sym_db.RegisterMessage(V3AlexaCookingTemperatureSensor)
_sym_db.RegisterMessage(V3AlexaCookingTemperatureSensor.Directive)
_sym_db.RegisterMessage(V3AlexaCookingTemperatureSensor.Event)
_sym_db.RegisterMessage(V3AlexaCookingTemperatureSensor.CookingTemperatureProperty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\035AlexaCookingTemperatureSensor'))
# @@protoc_insertion_point(module_scope)
