# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_capabilities/V3AlexaCookingTemperatureController.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3Temperature_pb2 as v3avs__types_dot_V3Temperature__pb2
from v3avs_types import V3TimeInterval_pb2 as v3avs__types_dot_V3TimeInterval__pb2
from v3avs_types import V3CookingMode_pb2 as v3avs__types_dot_V3CookingMode__pb2
from v3avs_types import V3FoodItem_pb2 as v3avs__types_dot_V3FoodItem__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_capabilities/V3AlexaCookingTemperatureController.proto',
  package='v3avs_capabilities',
  syntax='proto3',
  serialized_pb=_b('\n<v3avs_capabilities/V3AlexaCookingTemperatureController.proto\x12\x12v3avs_capabilities\x1a\x1fv3avs_types/V3Temperature.proto\x1a v3avs_types/V3TimeInterval.proto\x1a\x1fv3avs_types/V3CookingMode.proto\x1a\x1cv3avs_types/V3FoodItem.proto\"\xfc\x07\n#V3AlexaCookingTemperatureController\x1a\xd7\x02\n\tDirective\x12]\n\x0e\x64irective_name\x18\x01 \x01(\x0e\x32\x45.v3avs_capabilities.V3AlexaCookingTemperatureController.DirectiveName\x12h\n\x13\x63ook_by_temperature\x18\x02 \x01(\x0b\x32I.v3avs_capabilities.V3AlexaCookingTemperatureController.CookByTemperatureH\x00\x12v\n\x1a\x61\x64just_cooking_temperature\x18\x03 \x01(\x0b\x32P.v3avs_capabilities.V3AlexaCookingTemperatureController.AdjustCookingTemperatureH\x00\x42\t\n\x07payload\x1a\xb1\x01\n\x11\x43ookByTemperature\x12>\n\x1atarget_cooking_temperature\x18\x01 \x01(\x0b\x32\x1a.v3avs_types.V3Temperature\x12\x30\n\x0c\x63ooking_mode\x18\x02 \x01(\x0b\x32\x1a.v3avs_types.V3CookingMode\x12*\n\tfood_item\x18\x03 \x01(\x0b\x32\x17.v3avs_types.V3FoodItem\x1a`\n\x18\x41\x64justCookingTemperature\x12\x44\n target_cooking_temperature_delta\x18\x01 \x01(\x0b\x32\x1a.v3avs_types.V3Temperature\x1a\x07\n\x05\x45vent\x1a\x62\n TargetCookingTemperatureProperty\x12>\n\x1atarget_cooking_temperature\x18\x01 \x01(\x0b\x32\x1a.v3avs_types.V3Temperature\x1aY\n\x1bPreheatTimeIntervalProperty\x12:\n\x15preheat_time_interval\x18\x01 \x01(\x0b\x32\x1b.v3avs_types.V3TimeInterval\"H\n\rDirectiveName\x12\x17\n\x13\x43OOK_BY_TEMPERATURE\x10\x00\x12\x1e\n\x1a\x41\x44JUST_COOKING_TEMPERATURE\x10\x01\"S\n\x0cPropertyName\x12#\n\x1fTARGET_COOKING_TEMPERATURE_PROP\x10\x00\x12\x1e\n\x1aPREHEAT_TIME_INTERVAL_PROP\x10\x01\x42O\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB!AlexaCookingTemperatureControllerb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3Temperature__pb2.DESCRIPTOR,v3avs__types_dot_V3TimeInterval__pb2.DESCRIPTOR,v3avs__types_dot_V3CookingMode__pb2.DESCRIPTOR,v3avs__types_dot_V3FoodItem__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVENAME = _descriptor.EnumDescriptor(
  name='DirectiveName',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.DirectiveName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COOK_BY_TEMPERATURE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADJUST_COOKING_TEMPERATURE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1078,
  serialized_end=1150,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVENAME)

_V3ALEXACOOKINGTEMPERATURECONTROLLER_PROPERTYNAME = _descriptor.EnumDescriptor(
  name='PropertyName',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.PropertyName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TARGET_COOKING_TEMPERATURE_PROP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREHEAT_TIME_INTERVAL_PROP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1152,
  serialized_end=1235,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXACOOKINGTEMPERATURECONTROLLER_PROPERTYNAME)


_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE = _descriptor.Descriptor(
  name='Directive',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.Directive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='directive_name', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.Directive.directive_name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cook_by_temperature', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.Directive.cook_by_temperature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adjust_cooking_temperature', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.Directive.adjust_cooking_temperature', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.Directive.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=255,
  serialized_end=598,
)

_V3ALEXACOOKINGTEMPERATURECONTROLLER_COOKBYTEMPERATURE = _descriptor.Descriptor(
  name='CookByTemperature',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.CookByTemperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_cooking_temperature', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.CookByTemperature.target_cooking_temperature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cooking_mode', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.CookByTemperature.cooking_mode', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='food_item', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.CookByTemperature.food_item', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=778,
)

_V3ALEXACOOKINGTEMPERATURECONTROLLER_ADJUSTCOOKINGTEMPERATURE = _descriptor.Descriptor(
  name='AdjustCookingTemperature',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.AdjustCookingTemperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_cooking_temperature_delta', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.AdjustCookingTemperature.target_cooking_temperature_delta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=780,
  serialized_end=876,
)

_V3ALEXACOOKINGTEMPERATURECONTROLLER_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=878,
  serialized_end=885,
)

_V3ALEXACOOKINGTEMPERATURECONTROLLER_TARGETCOOKINGTEMPERATUREPROPERTY = _descriptor.Descriptor(
  name='TargetCookingTemperatureProperty',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.TargetCookingTemperatureProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_cooking_temperature', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.TargetCookingTemperatureProperty.target_cooking_temperature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=887,
  serialized_end=985,
)

_V3ALEXACOOKINGTEMPERATURECONTROLLER_PREHEATTIMEINTERVALPROPERTY = _descriptor.Descriptor(
  name='PreheatTimeIntervalProperty',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.PreheatTimeIntervalProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preheat_time_interval', full_name='v3avs_capabilities.V3AlexaCookingTemperatureController.PreheatTimeIntervalProperty.preheat_time_interval', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=987,
  serialized_end=1076,
)

_V3ALEXACOOKINGTEMPERATURECONTROLLER = _descriptor.Descriptor(
  name='V3AlexaCookingTemperatureController',
  full_name='v3avs_capabilities.V3AlexaCookingTemperatureController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE, _V3ALEXACOOKINGTEMPERATURECONTROLLER_COOKBYTEMPERATURE, _V3ALEXACOOKINGTEMPERATURECONTROLLER_ADJUSTCOOKINGTEMPERATURE, _V3ALEXACOOKINGTEMPERATURECONTROLLER_EVENT, _V3ALEXACOOKINGTEMPERATURECONTROLLER_TARGETCOOKINGTEMPERATUREPROPERTY, _V3ALEXACOOKINGTEMPERATURECONTROLLER_PREHEATTIMEINTERVALPROPERTY, ],
  enum_types=[
    _V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVENAME,
    _V3ALEXACOOKINGTEMPERATURECONTROLLER_PROPERTYNAME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=1235,
)

_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.fields_by_name['directive_name'].enum_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVENAME
_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.fields_by_name['cook_by_temperature'].message_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER_COOKBYTEMPERATURE
_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.fields_by_name['adjust_cooking_temperature'].message_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER_ADJUSTCOOKINGTEMPERATURE
_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.containing_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER
_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.oneofs_by_name['payload'].fields.append(
  _V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.fields_by_name['cook_by_temperature'])
_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.fields_by_name['cook_by_temperature'].containing_oneof = _V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.oneofs_by_name['payload']
_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.oneofs_by_name['payload'].fields.append(
  _V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.fields_by_name['adjust_cooking_temperature'])
_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.fields_by_name['adjust_cooking_temperature'].containing_oneof = _V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE.oneofs_by_name['payload']
_V3ALEXACOOKINGTEMPERATURECONTROLLER_COOKBYTEMPERATURE.fields_by_name['target_cooking_temperature'].message_type = v3avs__types_dot_V3Temperature__pb2._V3TEMPERATURE
_V3ALEXACOOKINGTEMPERATURECONTROLLER_COOKBYTEMPERATURE.fields_by_name['cooking_mode'].message_type = v3avs__types_dot_V3CookingMode__pb2._V3COOKINGMODE
_V3ALEXACOOKINGTEMPERATURECONTROLLER_COOKBYTEMPERATURE.fields_by_name['food_item'].message_type = v3avs__types_dot_V3FoodItem__pb2._V3FOODITEM
_V3ALEXACOOKINGTEMPERATURECONTROLLER_COOKBYTEMPERATURE.containing_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER
_V3ALEXACOOKINGTEMPERATURECONTROLLER_ADJUSTCOOKINGTEMPERATURE.fields_by_name['target_cooking_temperature_delta'].message_type = v3avs__types_dot_V3Temperature__pb2._V3TEMPERATURE
_V3ALEXACOOKINGTEMPERATURECONTROLLER_ADJUSTCOOKINGTEMPERATURE.containing_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER
_V3ALEXACOOKINGTEMPERATURECONTROLLER_EVENT.containing_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER
_V3ALEXACOOKINGTEMPERATURECONTROLLER_TARGETCOOKINGTEMPERATUREPROPERTY.fields_by_name['target_cooking_temperature'].message_type = v3avs__types_dot_V3Temperature__pb2._V3TEMPERATURE
_V3ALEXACOOKINGTEMPERATURECONTROLLER_TARGETCOOKINGTEMPERATUREPROPERTY.containing_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER
_V3ALEXACOOKINGTEMPERATURECONTROLLER_PREHEATTIMEINTERVALPROPERTY.fields_by_name['preheat_time_interval'].message_type = v3avs__types_dot_V3TimeInterval__pb2._V3TIMEINTERVAL
_V3ALEXACOOKINGTEMPERATURECONTROLLER_PREHEATTIMEINTERVALPROPERTY.containing_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER
_V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVENAME.containing_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER
_V3ALEXACOOKINGTEMPERATURECONTROLLER_PROPERTYNAME.containing_type = _V3ALEXACOOKINGTEMPERATURECONTROLLER
DESCRIPTOR.message_types_by_name['V3AlexaCookingTemperatureController'] = _V3ALEXACOOKINGTEMPERATURECONTROLLER

V3AlexaCookingTemperatureController = _reflection.GeneratedProtocolMessageType('V3AlexaCookingTemperatureController', (_message.Message,), dict(

  Directive = _reflection.GeneratedProtocolMessageType('Directive', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURECONTROLLER_DIRECTIVE,
    __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureController.Directive)
    ))
  ,

  CookByTemperature = _reflection.GeneratedProtocolMessageType('CookByTemperature', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURECONTROLLER_COOKBYTEMPERATURE,
    __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureController.CookByTemperature)
    ))
  ,

  AdjustCookingTemperature = _reflection.GeneratedProtocolMessageType('AdjustCookingTemperature', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURECONTROLLER_ADJUSTCOOKINGTEMPERATURE,
    __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureController.AdjustCookingTemperature)
    ))
  ,

  Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURECONTROLLER_EVENT,
    __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureController.Event)
    ))
  ,

  TargetCookingTemperatureProperty = _reflection.GeneratedProtocolMessageType('TargetCookingTemperatureProperty', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURECONTROLLER_TARGETCOOKINGTEMPERATUREPROPERTY,
    __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureController.TargetCookingTemperatureProperty)
    ))
  ,

  PreheatTimeIntervalProperty = _reflection.GeneratedProtocolMessageType('PreheatTimeIntervalProperty', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURECONTROLLER_PREHEATTIMEINTERVALPROPERTY,
    __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureController.PreheatTimeIntervalProperty)
    ))
  ,
  DESCRIPTOR = _V3ALEXACOOKINGTEMPERATURECONTROLLER,
  __module__ = 'v3avs_capabilities.V3AlexaCookingTemperatureController_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingTemperatureController)
  ))
_sym_db.RegisterMessage(V3AlexaCookingTemperatureController)
_sym_db.RegisterMessage(V3AlexaCookingTemperatureController.Directive)
_sym_db.RegisterMessage(V3AlexaCookingTemperatureController.CookByTemperature)
_sym_db.RegisterMessage(V3AlexaCookingTemperatureController.AdjustCookingTemperature)
_sym_db.RegisterMessage(V3AlexaCookingTemperatureController.Event)
_sym_db.RegisterMessage(V3AlexaCookingTemperatureController.TargetCookingTemperatureProperty)
_sym_db.RegisterMessage(V3AlexaCookingTemperatureController.PreheatTimeIntervalProperty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB!AlexaCookingTemperatureController'))
# @@protoc_insertion_point(module_scope)
