# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_capabilities/V3AlexaRangeController.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3Range_pb2 as v3avs__types_dot_V3Range__pb2
from v3avs_types import V3RangeDelta_pb2 as v3avs__types_dot_V3RangeDelta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_capabilities/V3AlexaRangeController.proto',
  package='v3avs_capabilities',
  syntax='proto3',
  serialized_pb=_b('\n/v3avs_capabilities/V3AlexaRangeController.proto\x12\x12v3avs_capabilities\x1a\x19v3avs_types/V3Range.proto\x1a\x1ev3avs_types/V3RangeDelta.proto\"\xe1\x04\n\x16V3AlexaRangeController\x1a\x98\x02\n\tDirective\x12P\n\x0e\x64irective_name\x18\x01 \x01(\x0e\x32\x38.v3avs_capabilities.V3AlexaRangeController.DirectiveName\x12S\n\x0fset_range_value\x18\x02 \x01(\x0b\x32\x38.v3avs_capabilities.V3AlexaRangeController.SetRangeValueH\x00\x12Y\n\x12\x61\x64just_range_value\x18\x03 \x01(\x0b\x32;.v3avs_capabilities.V3AlexaRangeController.AdjustRangeValueH\x00\x42\t\n\x07payload\x1a:\n\rSetRangeValue\x12)\n\x0brange_value\x18\x01 \x01(\x0b\x32\x14.v3avs_types.V3Range\x1a\x42\n\x10\x41\x64justRangeValue\x12.\n\x0brange_delta\x18\x01 \x01(\x0b\x32\x19.v3avs_types.V3RangeDelta\x1a\x07\n\x05\x45vent\x1a?\n\x12RangeValueProperty\x12)\n\x0brange_value\x18\x01 \x01(\x0b\x32\x14.v3avs_types.V3Range\"<\n\rDirectiveName\x12\x13\n\x0fSET_RANGE_VALUE\x10\x00\x12\x16\n\x12\x41\x44JUST_RANGE_VALUE\x10\x01\"$\n\x0cPropertyName\x12\x14\n\x10RANGE_VALUE_PROP\x10\x00\x42\x42\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\x14\x41lexaRangeControllerb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3Range__pb2.DESCRIPTOR,v3avs__types_dot_V3RangeDelta__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ALEXARANGECONTROLLER_DIRECTIVENAME = _descriptor.EnumDescriptor(
  name='DirectiveName',
  full_name='v3avs_capabilities.V3AlexaRangeController.DirectiveName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SET_RANGE_VALUE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADJUST_RANGE_VALUE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=642,
  serialized_end=702,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXARANGECONTROLLER_DIRECTIVENAME)

_V3ALEXARANGECONTROLLER_PROPERTYNAME = _descriptor.EnumDescriptor(
  name='PropertyName',
  full_name='v3avs_capabilities.V3AlexaRangeController.PropertyName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RANGE_VALUE_PROP', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=704,
  serialized_end=740,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXARANGECONTROLLER_PROPERTYNAME)


_V3ALEXARANGECONTROLLER_DIRECTIVE = _descriptor.Descriptor(
  name='Directive',
  full_name='v3avs_capabilities.V3AlexaRangeController.Directive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='directive_name', full_name='v3avs_capabilities.V3AlexaRangeController.Directive.directive_name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_range_value', full_name='v3avs_capabilities.V3AlexaRangeController.Directive.set_range_value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adjust_range_value', full_name='v3avs_capabilities.V3AlexaRangeController.Directive.adjust_range_value', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='v3avs_capabilities.V3AlexaRangeController.Directive.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=158,
  serialized_end=438,
)

_V3ALEXARANGECONTROLLER_SETRANGEVALUE = _descriptor.Descriptor(
  name='SetRangeValue',
  full_name='v3avs_capabilities.V3AlexaRangeController.SetRangeValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='range_value', full_name='v3avs_capabilities.V3AlexaRangeController.SetRangeValue.range_value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=498,
)

_V3ALEXARANGECONTROLLER_ADJUSTRANGEVALUE = _descriptor.Descriptor(
  name='AdjustRangeValue',
  full_name='v3avs_capabilities.V3AlexaRangeController.AdjustRangeValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='range_delta', full_name='v3avs_capabilities.V3AlexaRangeController.AdjustRangeValue.range_delta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=566,
)

_V3ALEXARANGECONTROLLER_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='v3avs_capabilities.V3AlexaRangeController.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=568,
  serialized_end=575,
)

_V3ALEXARANGECONTROLLER_RANGEVALUEPROPERTY = _descriptor.Descriptor(
  name='RangeValueProperty',
  full_name='v3avs_capabilities.V3AlexaRangeController.RangeValueProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='range_value', full_name='v3avs_capabilities.V3AlexaRangeController.RangeValueProperty.range_value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=640,
)

_V3ALEXARANGECONTROLLER = _descriptor.Descriptor(
  name='V3AlexaRangeController',
  full_name='v3avs_capabilities.V3AlexaRangeController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_V3ALEXARANGECONTROLLER_DIRECTIVE, _V3ALEXARANGECONTROLLER_SETRANGEVALUE, _V3ALEXARANGECONTROLLER_ADJUSTRANGEVALUE, _V3ALEXARANGECONTROLLER_EVENT, _V3ALEXARANGECONTROLLER_RANGEVALUEPROPERTY, ],
  enum_types=[
    _V3ALEXARANGECONTROLLER_DIRECTIVENAME,
    _V3ALEXARANGECONTROLLER_PROPERTYNAME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=740,
)

_V3ALEXARANGECONTROLLER_DIRECTIVE.fields_by_name['directive_name'].enum_type = _V3ALEXARANGECONTROLLER_DIRECTIVENAME
_V3ALEXARANGECONTROLLER_DIRECTIVE.fields_by_name['set_range_value'].message_type = _V3ALEXARANGECONTROLLER_SETRANGEVALUE
_V3ALEXARANGECONTROLLER_DIRECTIVE.fields_by_name['adjust_range_value'].message_type = _V3ALEXARANGECONTROLLER_ADJUSTRANGEVALUE
_V3ALEXARANGECONTROLLER_DIRECTIVE.containing_type = _V3ALEXARANGECONTROLLER
_V3ALEXARANGECONTROLLER_DIRECTIVE.oneofs_by_name['payload'].fields.append(
  _V3ALEXARANGECONTROLLER_DIRECTIVE.fields_by_name['set_range_value'])
_V3ALEXARANGECONTROLLER_DIRECTIVE.fields_by_name['set_range_value'].containing_oneof = _V3ALEXARANGECONTROLLER_DIRECTIVE.oneofs_by_name['payload']
_V3ALEXARANGECONTROLLER_DIRECTIVE.oneofs_by_name['payload'].fields.append(
  _V3ALEXARANGECONTROLLER_DIRECTIVE.fields_by_name['adjust_range_value'])
_V3ALEXARANGECONTROLLER_DIRECTIVE.fields_by_name['adjust_range_value'].containing_oneof = _V3ALEXARANGECONTROLLER_DIRECTIVE.oneofs_by_name['payload']
_V3ALEXARANGECONTROLLER_SETRANGEVALUE.fields_by_name['range_value'].message_type = v3avs__types_dot_V3Range__pb2._V3RANGE
_V3ALEXARANGECONTROLLER_SETRANGEVALUE.containing_type = _V3ALEXARANGECONTROLLER
_V3ALEXARANGECONTROLLER_ADJUSTRANGEVALUE.fields_by_name['range_delta'].message_type = v3avs__types_dot_V3RangeDelta__pb2._V3RANGEDELTA
_V3ALEXARANGECONTROLLER_ADJUSTRANGEVALUE.containing_type = _V3ALEXARANGECONTROLLER
_V3ALEXARANGECONTROLLER_EVENT.containing_type = _V3ALEXARANGECONTROLLER
_V3ALEXARANGECONTROLLER_RANGEVALUEPROPERTY.fields_by_name['range_value'].message_type = v3avs__types_dot_V3Range__pb2._V3RANGE
_V3ALEXARANGECONTROLLER_RANGEVALUEPROPERTY.containing_type = _V3ALEXARANGECONTROLLER
_V3ALEXARANGECONTROLLER_DIRECTIVENAME.containing_type = _V3ALEXARANGECONTROLLER
_V3ALEXARANGECONTROLLER_PROPERTYNAME.containing_type = _V3ALEXARANGECONTROLLER
DESCRIPTOR.message_types_by_name['V3AlexaRangeController'] = _V3ALEXARANGECONTROLLER

V3AlexaRangeController = _reflection.GeneratedProtocolMessageType('V3AlexaRangeController', (_message.Message,), dict(

  Directive = _reflection.GeneratedProtocolMessageType('Directive', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXARANGECONTROLLER_DIRECTIVE,
    __module__ = 'v3avs_capabilities.V3AlexaRangeController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaRangeController.Directive)
    ))
  ,

  SetRangeValue = _reflection.GeneratedProtocolMessageType('SetRangeValue', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXARANGECONTROLLER_SETRANGEVALUE,
    __module__ = 'v3avs_capabilities.V3AlexaRangeController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaRangeController.SetRangeValue)
    ))
  ,

  AdjustRangeValue = _reflection.GeneratedProtocolMessageType('AdjustRangeValue', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXARANGECONTROLLER_ADJUSTRANGEVALUE,
    __module__ = 'v3avs_capabilities.V3AlexaRangeController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaRangeController.AdjustRangeValue)
    ))
  ,

  Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXARANGECONTROLLER_EVENT,
    __module__ = 'v3avs_capabilities.V3AlexaRangeController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaRangeController.Event)
    ))
  ,

  RangeValueProperty = _reflection.GeneratedProtocolMessageType('RangeValueProperty', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXARANGECONTROLLER_RANGEVALUEPROPERTY,
    __module__ = 'v3avs_capabilities.V3AlexaRangeController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaRangeController.RangeValueProperty)
    ))
  ,
  DESCRIPTOR = _V3ALEXARANGECONTROLLER,
  __module__ = 'v3avs_capabilities.V3AlexaRangeController_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaRangeController)
  ))
_sym_db.RegisterMessage(V3AlexaRangeController)
_sym_db.RegisterMessage(V3AlexaRangeController.Directive)
_sym_db.RegisterMessage(V3AlexaRangeController.SetRangeValue)
_sym_db.RegisterMessage(V3AlexaRangeController.AdjustRangeValue)
_sym_db.RegisterMessage(V3AlexaRangeController.Event)
_sym_db.RegisterMessage(V3AlexaRangeController.RangeValueProperty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\024AlexaRangeController'))
# @@protoc_insertion_point(module_scope)
