# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_capabilities/V3AlexaPercentageController.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3Percentage_pb2 as v3avs__types_dot_V3Percentage__pb2
from v3avs_types import V3PercentageDelta_pb2 as v3avs__types_dot_V3PercentageDelta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_capabilities/V3AlexaPercentageController.proto',
  package='v3avs_capabilities',
  syntax='proto3',
  serialized_pb=_b('\n4v3avs_capabilities/V3AlexaPercentageController.proto\x12\x12v3avs_capabilities\x1a\x1ev3avs_types/V3Percentage.proto\x1a#v3avs_types/V3PercentageDelta.proto\"\x82\x05\n\x1bV3AlexaPercentageController\x1a\xa5\x02\n\tDirective\x12U\n\x0e\x64irective_name\x18\x01 \x01(\x0e\x32=.v3avs_capabilities.V3AlexaPercentageController.DirectiveName\x12W\n\x0eset_percentage\x18\x02 \x01(\x0b\x32=.v3avs_capabilities.V3AlexaPercentageController.SetPercentageH\x00\x12]\n\x11\x61\x64just_percentage\x18\x03 \x01(\x0b\x32@.v3avs_capabilities.V3AlexaPercentageController.AdjustPercentageH\x00\x42\t\n\x07payload\x1a\x07\n\x05\x45vent\x1a>\n\rSetPercentage\x12-\n\npercentage\x18\x01 \x01(\x0b\x32\x19.v3avs_types.V3Percentage\x1aL\n\x10\x41\x64justPercentage\x12\x38\n\x10percentage_delta\x18\x01 \x01(\x0b\x32\x1e.v3avs_types.V3PercentageDelta\x1a\x43\n\x12PercentageProperty\x12-\n\npercentage\x18\x01 \x01(\x0b\x32\x19.v3avs_types.V3Percentage\":\n\rDirectiveName\x12\x12\n\x0eSET_PERCENTAGE\x10\x00\x12\x15\n\x11\x41\x44JUST_PERCENTAGE\x10\x01\"#\n\x0cPropertyName\x12\x13\n\x0fPERCENTAGE_PROP\x10\x00\x42G\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\x19\x41lexaPercentageControllerb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3Percentage__pb2.DESCRIPTOR,v3avs__types_dot_V3PercentageDelta__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVENAME = _descriptor.EnumDescriptor(
  name='DirectiveName',
  full_name='v3avs_capabilities.V3AlexaPercentageController.DirectiveName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SET_PERCENTAGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADJUST_PERCENTAGE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=693,
  serialized_end=751,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVENAME)

_V3ALEXAPERCENTAGECONTROLLER_PROPERTYNAME = _descriptor.EnumDescriptor(
  name='PropertyName',
  full_name='v3avs_capabilities.V3AlexaPercentageController.PropertyName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PERCENTAGE_PROP', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=753,
  serialized_end=788,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXAPERCENTAGECONTROLLER_PROPERTYNAME)


_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE = _descriptor.Descriptor(
  name='Directive',
  full_name='v3avs_capabilities.V3AlexaPercentageController.Directive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='directive_name', full_name='v3avs_capabilities.V3AlexaPercentageController.Directive.directive_name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_percentage', full_name='v3avs_capabilities.V3AlexaPercentageController.Directive.set_percentage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adjust_percentage', full_name='v3avs_capabilities.V3AlexaPercentageController.Directive.adjust_percentage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='v3avs_capabilities.V3AlexaPercentageController.Directive.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=178,
  serialized_end=471,
)

_V3ALEXAPERCENTAGECONTROLLER_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='v3avs_capabilities.V3AlexaPercentageController.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=480,
)

_V3ALEXAPERCENTAGECONTROLLER_SETPERCENTAGE = _descriptor.Descriptor(
  name='SetPercentage',
  full_name='v3avs_capabilities.V3AlexaPercentageController.SetPercentage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='percentage', full_name='v3avs_capabilities.V3AlexaPercentageController.SetPercentage.percentage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=544,
)

_V3ALEXAPERCENTAGECONTROLLER_ADJUSTPERCENTAGE = _descriptor.Descriptor(
  name='AdjustPercentage',
  full_name='v3avs_capabilities.V3AlexaPercentageController.AdjustPercentage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='percentage_delta', full_name='v3avs_capabilities.V3AlexaPercentageController.AdjustPercentage.percentage_delta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=622,
)

_V3ALEXAPERCENTAGECONTROLLER_PERCENTAGEPROPERTY = _descriptor.Descriptor(
  name='PercentageProperty',
  full_name='v3avs_capabilities.V3AlexaPercentageController.PercentageProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='percentage', full_name='v3avs_capabilities.V3AlexaPercentageController.PercentageProperty.percentage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=624,
  serialized_end=691,
)

_V3ALEXAPERCENTAGECONTROLLER = _descriptor.Descriptor(
  name='V3AlexaPercentageController',
  full_name='v3avs_capabilities.V3AlexaPercentageController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE, _V3ALEXAPERCENTAGECONTROLLER_EVENT, _V3ALEXAPERCENTAGECONTROLLER_SETPERCENTAGE, _V3ALEXAPERCENTAGECONTROLLER_ADJUSTPERCENTAGE, _V3ALEXAPERCENTAGECONTROLLER_PERCENTAGEPROPERTY, ],
  enum_types=[
    _V3ALEXAPERCENTAGECONTROLLER_DIRECTIVENAME,
    _V3ALEXAPERCENTAGECONTROLLER_PROPERTYNAME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=788,
)

_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.fields_by_name['directive_name'].enum_type = _V3ALEXAPERCENTAGECONTROLLER_DIRECTIVENAME
_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.fields_by_name['set_percentage'].message_type = _V3ALEXAPERCENTAGECONTROLLER_SETPERCENTAGE
_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.fields_by_name['adjust_percentage'].message_type = _V3ALEXAPERCENTAGECONTROLLER_ADJUSTPERCENTAGE
_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.containing_type = _V3ALEXAPERCENTAGECONTROLLER
_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.oneofs_by_name['payload'].fields.append(
  _V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.fields_by_name['set_percentage'])
_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.fields_by_name['set_percentage'].containing_oneof = _V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.oneofs_by_name['payload']
_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.oneofs_by_name['payload'].fields.append(
  _V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.fields_by_name['adjust_percentage'])
_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.fields_by_name['adjust_percentage'].containing_oneof = _V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE.oneofs_by_name['payload']
_V3ALEXAPERCENTAGECONTROLLER_EVENT.containing_type = _V3ALEXAPERCENTAGECONTROLLER
_V3ALEXAPERCENTAGECONTROLLER_SETPERCENTAGE.fields_by_name['percentage'].message_type = v3avs__types_dot_V3Percentage__pb2._V3PERCENTAGE
_V3ALEXAPERCENTAGECONTROLLER_SETPERCENTAGE.containing_type = _V3ALEXAPERCENTAGECONTROLLER
_V3ALEXAPERCENTAGECONTROLLER_ADJUSTPERCENTAGE.fields_by_name['percentage_delta'].message_type = v3avs__types_dot_V3PercentageDelta__pb2._V3PERCENTAGEDELTA
_V3ALEXAPERCENTAGECONTROLLER_ADJUSTPERCENTAGE.containing_type = _V3ALEXAPERCENTAGECONTROLLER
_V3ALEXAPERCENTAGECONTROLLER_PERCENTAGEPROPERTY.fields_by_name['percentage'].message_type = v3avs__types_dot_V3Percentage__pb2._V3PERCENTAGE
_V3ALEXAPERCENTAGECONTROLLER_PERCENTAGEPROPERTY.containing_type = _V3ALEXAPERCENTAGECONTROLLER
_V3ALEXAPERCENTAGECONTROLLER_DIRECTIVENAME.containing_type = _V3ALEXAPERCENTAGECONTROLLER
_V3ALEXAPERCENTAGECONTROLLER_PROPERTYNAME.containing_type = _V3ALEXAPERCENTAGECONTROLLER
DESCRIPTOR.message_types_by_name['V3AlexaPercentageController'] = _V3ALEXAPERCENTAGECONTROLLER

V3AlexaPercentageController = _reflection.GeneratedProtocolMessageType('V3AlexaPercentageController', (_message.Message,), dict(

  Directive = _reflection.GeneratedProtocolMessageType('Directive', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXAPERCENTAGECONTROLLER_DIRECTIVE,
    __module__ = 'v3avs_capabilities.V3AlexaPercentageController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaPercentageController.Directive)
    ))
  ,

  Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXAPERCENTAGECONTROLLER_EVENT,
    __module__ = 'v3avs_capabilities.V3AlexaPercentageController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaPercentageController.Event)
    ))
  ,

  SetPercentage = _reflection.GeneratedProtocolMessageType('SetPercentage', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXAPERCENTAGECONTROLLER_SETPERCENTAGE,
    __module__ = 'v3avs_capabilities.V3AlexaPercentageController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaPercentageController.SetPercentage)
    ))
  ,

  AdjustPercentage = _reflection.GeneratedProtocolMessageType('AdjustPercentage', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXAPERCENTAGECONTROLLER_ADJUSTPERCENTAGE,
    __module__ = 'v3avs_capabilities.V3AlexaPercentageController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaPercentageController.AdjustPercentage)
    ))
  ,

  PercentageProperty = _reflection.GeneratedProtocolMessageType('PercentageProperty', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXAPERCENTAGECONTROLLER_PERCENTAGEPROPERTY,
    __module__ = 'v3avs_capabilities.V3AlexaPercentageController_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaPercentageController.PercentageProperty)
    ))
  ,
  DESCRIPTOR = _V3ALEXAPERCENTAGECONTROLLER,
  __module__ = 'v3avs_capabilities.V3AlexaPercentageController_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaPercentageController)
  ))
_sym_db.RegisterMessage(V3AlexaPercentageController)
_sym_db.RegisterMessage(V3AlexaPercentageController.Directive)
_sym_db.RegisterMessage(V3AlexaPercentageController.Event)
_sym_db.RegisterMessage(V3AlexaPercentageController.SetPercentage)
_sym_db.RegisterMessage(V3AlexaPercentageController.AdjustPercentage)
_sym_db.RegisterMessage(V3AlexaPercentageController.PercentageProperty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB\031AlexaPercentageController'))
# @@protoc_insertion_point(module_scope)
