# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_capabilities/V3AlexaCookingFoodTemperatureSensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3Temperature_pb2 as v3avs__types_dot_V3Temperature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_capabilities/V3AlexaCookingFoodTemperatureSensor.proto',
  package='v3avs_capabilities',
  syntax='proto3',
  serialized_pb=_b('\n<v3avs_capabilities/V3AlexaCookingFoodTemperatureSensor.proto\x12\x12v3avs_capabilities\x1a\x1fv3avs_types/V3Temperature.proto\"\xb7\x01\n#V3AlexaCookingFoodTemperatureSensor\x1a\x0b\n\tDirective\x1a\x07\n\x05\x45vent\x1aO\n\x17\x46oodTemperatureProperty\x12\x34\n\x10\x66ood_temperature\x18\x01 \x01(\x0b\x32\x1a.v3avs_types.V3Temperature\")\n\x0cPropertyName\x12\x19\n\x15\x46OOD_TEMPERATURE_PROP\x10\x00\x42O\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB!AlexaCookingFoodTemperatureSensorb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3Temperature__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ALEXACOOKINGFOODTEMPERATURESENSOR_PROPERTYNAME = _descriptor.EnumDescriptor(
  name='PropertyName',
  full_name='v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor.PropertyName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FOOD_TEMPERATURE_PROP', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=260,
  serialized_end=301,
)
_sym_db.RegisterEnumDescriptor(_V3ALEXACOOKINGFOODTEMPERATURESENSOR_PROPERTYNAME)


_V3ALEXACOOKINGFOODTEMPERATURESENSOR_DIRECTIVE = _descriptor.Descriptor(
  name='Directive',
  full_name='v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor.Directive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=168,
)

_V3ALEXACOOKINGFOODTEMPERATURESENSOR_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=177,
)

_V3ALEXACOOKINGFOODTEMPERATURESENSOR_FOODTEMPERATUREPROPERTY = _descriptor.Descriptor(
  name='FoodTemperatureProperty',
  full_name='v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor.FoodTemperatureProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='food_temperature', full_name='v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor.FoodTemperatureProperty.food_temperature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=258,
)

_V3ALEXACOOKINGFOODTEMPERATURESENSOR = _descriptor.Descriptor(
  name='V3AlexaCookingFoodTemperatureSensor',
  full_name='v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_V3ALEXACOOKINGFOODTEMPERATURESENSOR_DIRECTIVE, _V3ALEXACOOKINGFOODTEMPERATURESENSOR_EVENT, _V3ALEXACOOKINGFOODTEMPERATURESENSOR_FOODTEMPERATUREPROPERTY, ],
  enum_types=[
    _V3ALEXACOOKINGFOODTEMPERATURESENSOR_PROPERTYNAME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=301,
)

_V3ALEXACOOKINGFOODTEMPERATURESENSOR_DIRECTIVE.containing_type = _V3ALEXACOOKINGFOODTEMPERATURESENSOR
_V3ALEXACOOKINGFOODTEMPERATURESENSOR_EVENT.containing_type = _V3ALEXACOOKINGFOODTEMPERATURESENSOR
_V3ALEXACOOKINGFOODTEMPERATURESENSOR_FOODTEMPERATUREPROPERTY.fields_by_name['food_temperature'].message_type = v3avs__types_dot_V3Temperature__pb2._V3TEMPERATURE
_V3ALEXACOOKINGFOODTEMPERATURESENSOR_FOODTEMPERATUREPROPERTY.containing_type = _V3ALEXACOOKINGFOODTEMPERATURESENSOR
_V3ALEXACOOKINGFOODTEMPERATURESENSOR_PROPERTYNAME.containing_type = _V3ALEXACOOKINGFOODTEMPERATURESENSOR
DESCRIPTOR.message_types_by_name['V3AlexaCookingFoodTemperatureSensor'] = _V3ALEXACOOKINGFOODTEMPERATURESENSOR

V3AlexaCookingFoodTemperatureSensor = _reflection.GeneratedProtocolMessageType('V3AlexaCookingFoodTemperatureSensor', (_message.Message,), dict(

  Directive = _reflection.GeneratedProtocolMessageType('Directive', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGFOODTEMPERATURESENSOR_DIRECTIVE,
    __module__ = 'v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor.Directive)
    ))
  ,

  Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGFOODTEMPERATURESENSOR_EVENT,
    __module__ = 'v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor.Event)
    ))
  ,

  FoodTemperatureProperty = _reflection.GeneratedProtocolMessageType('FoodTemperatureProperty', (_message.Message,), dict(
    DESCRIPTOR = _V3ALEXACOOKINGFOODTEMPERATURESENSOR_FOODTEMPERATUREPROPERTY,
    __module__ = 'v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor_pb2'
    # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor.FoodTemperatureProperty)
    ))
  ,
  DESCRIPTOR = _V3ALEXACOOKINGFOODTEMPERATURESENSOR,
  __module__ = 'v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_capabilities.V3AlexaCookingFoodTemperatureSensor)
  ))
_sym_db.RegisterMessage(V3AlexaCookingFoodTemperatureSensor)
_sym_db.RegisterMessage(V3AlexaCookingFoodTemperatureSensor.Directive)
_sym_db.RegisterMessage(V3AlexaCookingFoodTemperatureSensor.Event)
_sym_db.RegisterMessage(V3AlexaCookingFoodTemperatureSensor.FoodTemperatureProperty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.amazon.proto.avs.v3.v3avs_capabilitiesB!AlexaCookingFoodTemperatureSensor'))
# @@protoc_insertion_point(module_scope)
