format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_disp_slcd1-xpro_8x24}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: slcd_display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_slcd}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: Segmented Display}
- type: ElementPosition
  attributes: {x: '569', y: '198', id: gfx_disp_slcd1-xpro_8x24}
