format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_slcd}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: EnableBiasBuffer}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Segmented Display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_disp_slcd1-xpro_8x24}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: slcd_display}
- type: ElementPosition
  attributes: {x: '759', y: '197', id: le_gfx_slcd}
