format_version: v1.0
configName: sam_l22_xpro
folderName: sam_l22_xpro
frameworkPath: C:\Dev\harmony3
processor: ATSAML22N18A
projectName: sam_l22_xpro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAML22_DFP\3.5.68\atdf\ATSAML22N18A.atdf
