format_version: v1.0
type: UniqueComponent
attributes: {id: sys_fs}
children:
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: sys_fs_DRV_MEDIA_dependency}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: drv_sdspi_0, targetAttachmentID: drv_media}
- type: ElementPosition
  attributes: {x: '429', y: '261', id: sys_fs}
