format_version: v1.0
type: UniqueComponent
attributes: {id: qspi}
children:
- type: Symbols
  children:
  - type: Comment
    attributes: {id: QSPI_CLK_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** QSPI Clock Frequency Is Set To 50.0 MHz for Master
            Clock Frequency At 150.0 MHz'}
  - type: Integer
    attributes: {id: QSPI_CLK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '50000000'}
  - type: KeyValueSet
    attributes: {id: QSPI_CPOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '0'}
- type: ElementPosition
  attributes: {x: '190', y: '60', id: qspi}
