format_version: v1.0
configName: pic32cm_le00
folderName: pic32cm_le00_securegateway_client
frameworkPath: D:\H3_MCC_01
processor: PIC32CM5164LE00100
projectName: pic32cm_le00_securegateway_client
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-LE_DFP\1.1.162\atdf\PIC32CM5164LE00100.atdf
