format_version: v1.0
type: UniqueComponent
attributes: {id: pm}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: PM_SLEEP_IDLE_OPTION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
- type: ElementPosition
  attributes: {x: '26', y: '300', id: pm}
