configName: sam_d21_xpro
folderName: sam_d21_xpro
format_version: v1.0
frameworkPath: D:\Projects\git_hub
processor: ATSAMD21J18A
projectName: low_power_sam_d21_xpro
settings:
  PackageFilter: audio;bsp;bt;core;crypto;cryptoauthlib;csp;gfx;gfx_apps;reference_apps;usb;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.116\samd21a\atdf\ATSAMD21J18A.atdf
