format_version: v1.0
configName: sam_c21_xpro
folderName: sam_c21_xpro
frameworkPath: D:\LTBD\Harmony_public_release
processor: ATSAMC21J18A
projectName: sam_c21_xpro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMC21_DFP\3.5.95\samc21\atdf\ATSAMC21J18A.atdf
