# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3ColorTemperatureInKelvin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3ColorTemperatureInKelvin.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n,v3avs_types/V3ColorTemperatureInKelvin.proto\x12\x0bv3avs_types\"+\n\x1aV3ColorTemperatureInKelvin\x12\r\n\x05value\x18\x01 \x01(\rB?\n#com.amazon.proto.avs.v3.v3avs_typesB\x18\x43olorTemperatureInKelvinb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_V3COLORTEMPERATUREINKELVIN = _descriptor.Descriptor(
  name='V3ColorTemperatureInKelvin',
  full_name='v3avs_types.V3ColorTemperatureInKelvin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v3avs_types.V3ColorTemperatureInKelvin.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['V3ColorTemperatureInKelvin'] = _V3COLORTEMPERATUREINKELVIN

V3ColorTemperatureInKelvin = _reflection.GeneratedProtocolMessageType('V3ColorTemperatureInKelvin', (_message.Message,), dict(
  DESCRIPTOR = _V3COLORTEMPERATUREINKELVIN,
  __module__ = 'v3avs_types.V3ColorTemperatureInKelvin_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3ColorTemperatureInKelvin)
  ))
_sym_db.RegisterMessage(V3ColorTemperatureInKelvin)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\030ColorTemperatureInKelvin'))
# @@protoc_insertion_point(module_scope)
