# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3CookingMode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3CookingMode.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x1fv3avs_types/V3CookingMode.proto\x12\x0bv3avs_types\"\xe6\x04\n\rV3CookingMode\x12/\n\x05value\x18\x01 \x01(\x0e\x32 .v3avs_types.V3CookingMode.Value\x12\x13\n\x0b\x63ustom_name\x18\x02 \x01(\t\"\x8e\x04\n\x05Value\x12\x0c\n\x08TIMECOOK\x10\x00\x12\n\n\x06PRESET\x10\x01\x12\x0b\n\x07\x44\x45\x46ROST\x10\x02\x12\n\n\x06REHEAT\x10\x03\x12\x08\n\x04\x42\x41KE\x10\x04\x12\t\n\x05\x42ROIL\x10\x05\x12\t\n\x05ROAST\x10\x06\x12\t\n\x05TOAST\x10\x07\x12\t\n\x05STEAM\x10\x08\x12\x0c\n\x08SLOWCOOK\x10\t\x12\r\n\tSOUS_VIDE\x10\n\x12\x0c\n\x08PRESSURE\x10\x0b\x12\t\n\x05SAUTE\x10\x0c\x12\x08\n\x04SEAR\x10\r\x12\x08\n\x04\x42REW\x10\x0e\x12\t\n\x05SMOKE\x10\x0f\x12\x08\n\x04WARM\x10\x10\x12\n\n\x06\x43USTOM\x10\x11\x12\x07\n\x03OFF\x10\x12\x12\x0b\n\x07\x41IR_FRY\x10\x13\x12\x08\n\x04\x42OIL\x10\x14\x12\n\n\x06\x42LANCH\x10\x15\x12\t\n\x05\x42ROWN\x10\x16\x12\x07\n\x03\x43\x41N\x10\x17\x12\x13\n\x0f\x43ONVECTION_BAKE\x10\x18\x12\x14\n\x10\x43ONVECTION_BROIL\x10\x19\x12\x14\n\x10\x43ONVECTION_ROAST\x10\x1a\x12\x14\n\x10\x43ONVECTION_STEAM\x10\x1b\x12\x08\n\x04\x43URE\x10\x1c\x12\r\n\tDEHYDRATE\x10\x1d\x12\x0b\n\x07\x46\x45RMENT\x10\x1e\x12\x07\n\x03\x46RY\x10\x1f\x12\t\n\x05GRILL\x10 \x12\x0c\n\x08INCUBATE\x10!\x12\x08\n\x04MELT\x10\"\x12\t\n\x05PROOF\x10#\x12\n\n\x06SIMMER\x10$\x12\n\n\x06SOFTEN\x10%\x12\r\n\tSTERILIZE\x10&\x12\x08\n\x04STEW\x10\'\x12\x0c\n\x08STIR_FRY\x10(B2\n#com.amazon.proto.avs.v3.v3avs_typesB\x0b\x43ookingModeb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3COOKINGMODE_VALUE = _descriptor.EnumDescriptor(
  name='Value',
  full_name='v3avs_types.V3CookingMode.Value',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TIMECOOK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRESET', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEFROST', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REHEAT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAKE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BROIL', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROAST', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOAST', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEAM', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLOWCOOK', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOUS_VIDE', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRESSURE', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAUTE', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEAR', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BREW', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SMOKE', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARM', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AIR_FRY', index=19, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOIL', index=20, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLANCH', index=21, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BROWN', index=22, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAN', index=23, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONVECTION_BAKE', index=24, number=24,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONVECTION_BROIL', index=25, number=25,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONVECTION_ROAST', index=26, number=26,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONVECTION_STEAM', index=27, number=27,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CURE', index=28, number=28,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEHYDRATE', index=29, number=29,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FERMENT', index=30, number=30,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRY', index=31, number=31,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRILL', index=32, number=32,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCUBATE', index=33, number=33,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MELT', index=34, number=34,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROOF', index=35, number=35,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMMER', index=36, number=36,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTEN', index=37, number=37,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STERILIZE', index=38, number=38,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEW', index=39, number=39,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STIR_FRY', index=40, number=40,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=137,
  serialized_end=663,
)
_sym_db.RegisterEnumDescriptor(_V3COOKINGMODE_VALUE)


_V3COOKINGMODE = _descriptor.Descriptor(
  name='V3CookingMode',
  full_name='v3avs_types.V3CookingMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v3avs_types.V3CookingMode.value', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_name', full_name='v3avs_types.V3CookingMode.custom_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _V3COOKINGMODE_VALUE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=663,
)

_V3COOKINGMODE.fields_by_name['value'].enum_type = _V3COOKINGMODE_VALUE
_V3COOKINGMODE_VALUE.containing_type = _V3COOKINGMODE
DESCRIPTOR.message_types_by_name['V3CookingMode'] = _V3COOKINGMODE

V3CookingMode = _reflection.GeneratedProtocolMessageType('V3CookingMode', (_message.Message,), dict(
  DESCRIPTOR = _V3COOKINGMODE,
  __module__ = 'v3avs_types.V3CookingMode_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3CookingMode)
  ))
_sym_db.RegisterMessage(V3CookingMode)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\013CookingMode'))
# @@protoc_insertion_point(module_scope)
