# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3Color.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3Color.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x19v3avs_types/V3Color.proto\x12\x0bv3avs_types\">\n\x07V3Color\x12\x0b\n\x03hue\x18\x01 \x01(\x01\x12\x12\n\nsaturation\x18\x02 \x01(\x01\x12\x12\n\nbrightness\x18\x03 \x01(\x01\x42,\n#com.amazon.proto.avs.v3.v3avs_typesB\x05\x43olorb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_V3COLOR = _descriptor.Descriptor(
  name='V3Color',
  full_name='v3avs_types.V3Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hue', full_name='v3avs_types.V3Color.hue', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='saturation', full_name='v3avs_types.V3Color.saturation', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brightness', full_name='v3avs_types.V3Color.brightness', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['V3Color'] = _V3COLOR

V3Color = _reflection.GeneratedProtocolMessageType('V3Color', (_message.Message,), dict(
  DESCRIPTOR = _V3COLOR,
  __module__ = 'v3avs_types.V3Color_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3Color)
  ))
_sym_db.RegisterMessage(V3Color)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\005Color'))
# @@protoc_insertion_point(module_scope)
