# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3EnumeratedPowerLevel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3EnumeratedPowerLevel.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n(v3avs_types/V3EnumeratedPowerLevel.proto\x12\x0bv3avs_types\"\x9d\x01\n\x16V3EnumeratedPowerLevel\x12\x38\n\x05value\x18\x01 \x01(\x0e\x32).v3avs_types.V3EnumeratedPowerLevel.Value\"I\n\x05Value\x12\x06\n\x02NA\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\x0b\n\x07MED_LOW\x10\x02\x12\n\n\x06MEDIUM\x10\x03\x12\x0c\n\x08MED_HIGH\x10\x04\x12\x08\n\x04HIGH\x10\x05\x42;\n#com.amazon.proto.avs.v3.v3avs_typesB\x14\x45numeratedPowerLevelb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ENUMERATEDPOWERLEVEL_VALUE = _descriptor.EnumDescriptor(
  name='Value',
  full_name='v3avs_types.V3EnumeratedPowerLevel.Value',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NA', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MED_LOW', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MED_HIGH', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=142,
  serialized_end=215,
)
_sym_db.RegisterEnumDescriptor(_V3ENUMERATEDPOWERLEVEL_VALUE)


_V3ENUMERATEDPOWERLEVEL = _descriptor.Descriptor(
  name='V3EnumeratedPowerLevel',
  full_name='v3avs_types.V3EnumeratedPowerLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v3avs_types.V3EnumeratedPowerLevel.value', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _V3ENUMERATEDPOWERLEVEL_VALUE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=215,
)

_V3ENUMERATEDPOWERLEVEL.fields_by_name['value'].enum_type = _V3ENUMERATEDPOWERLEVEL_VALUE
_V3ENUMERATEDPOWERLEVEL_VALUE.containing_type = _V3ENUMERATEDPOWERLEVEL
DESCRIPTOR.message_types_by_name['V3EnumeratedPowerLevel'] = _V3ENUMERATEDPOWERLEVEL

V3EnumeratedPowerLevel = _reflection.GeneratedProtocolMessageType('V3EnumeratedPowerLevel', (_message.Message,), dict(
  DESCRIPTOR = _V3ENUMERATEDPOWERLEVEL,
  __module__ = 'v3avs_types.V3EnumeratedPowerLevel_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3EnumeratedPowerLevel)
  ))
_sym_db.RegisterMessage(V3EnumeratedPowerLevel)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\024EnumeratedPowerLevel'))
# @@protoc_insertion_point(module_scope)
