# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3ItemQuantity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3Count_pb2 as v3avs__types_dot_V3Count__pb2
from v3avs_types import V3Weight_pb2 as v3avs__types_dot_V3Weight__pb2
from v3avs_types import V3Volume_pb2 as v3avs__types_dot_V3Volume__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3ItemQuantity.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n v3avs_types/V3ItemQuantity.proto\x12\x0bv3avs_types\x1a\x19v3avs_types/V3Count.proto\x1a\x1av3avs_types/V3Weight.proto\x1a\x1av3avs_types/V3Volume.proto\"\x88\x02\n\x0eV3ItemQuantity\x12?\n\rquantity_type\x18\x01 \x01(\x0e\x32(.v3avs_types.V3ItemQuantity.QuantityType\x12%\n\x05\x63ount\x18\x02 \x01(\x0b\x32\x14.v3avs_types.V3CountH\x00\x12\'\n\x06weight\x18\x03 \x01(\x0b\x32\x15.v3avs_types.V3WeightH\x00\x12\'\n\x06volume\x18\x04 \x01(\x0b\x32\x15.v3avs_types.V3VolumeH\x00\"1\n\x0cQuantityType\x12\t\n\x05\x43OUNT\x10\x00\x12\n\n\x06WEIGHT\x10\x01\x12\n\n\x06VOLUME\x10\x02\x42\t\n\x07payloadB3\n#com.amazon.proto.avs.v3.v3avs_typesB\x0cItemQuantityb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3Count__pb2.DESCRIPTOR,v3avs__types_dot_V3Weight__pb2.DESCRIPTOR,v3avs__types_dot_V3Volume__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3ITEMQUANTITY_QUANTITYTYPE = _descriptor.EnumDescriptor(
  name='QuantityType',
  full_name='v3avs_types.V3ItemQuantity.QuantityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COUNT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEIGHT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOLUME', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=337,
  serialized_end=386,
)
_sym_db.RegisterEnumDescriptor(_V3ITEMQUANTITY_QUANTITYTYPE)


_V3ITEMQUANTITY = _descriptor.Descriptor(
  name='V3ItemQuantity',
  full_name='v3avs_types.V3ItemQuantity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantity_type', full_name='v3avs_types.V3ItemQuantity.quantity_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='v3avs_types.V3ItemQuantity.count', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='v3avs_types.V3ItemQuantity.weight', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='v3avs_types.V3ItemQuantity.volume', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _V3ITEMQUANTITY_QUANTITYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='v3avs_types.V3ItemQuantity.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=133,
  serialized_end=397,
)

_V3ITEMQUANTITY.fields_by_name['quantity_type'].enum_type = _V3ITEMQUANTITY_QUANTITYTYPE
_V3ITEMQUANTITY.fields_by_name['count'].message_type = v3avs__types_dot_V3Count__pb2._V3COUNT
_V3ITEMQUANTITY.fields_by_name['weight'].message_type = v3avs__types_dot_V3Weight__pb2._V3WEIGHT
_V3ITEMQUANTITY.fields_by_name['volume'].message_type = v3avs__types_dot_V3Volume__pb2._V3VOLUME
_V3ITEMQUANTITY_QUANTITYTYPE.containing_type = _V3ITEMQUANTITY
_V3ITEMQUANTITY.oneofs_by_name['payload'].fields.append(
  _V3ITEMQUANTITY.fields_by_name['count'])
_V3ITEMQUANTITY.fields_by_name['count'].containing_oneof = _V3ITEMQUANTITY.oneofs_by_name['payload']
_V3ITEMQUANTITY.oneofs_by_name['payload'].fields.append(
  _V3ITEMQUANTITY.fields_by_name['weight'])
_V3ITEMQUANTITY.fields_by_name['weight'].containing_oneof = _V3ITEMQUANTITY.oneofs_by_name['payload']
_V3ITEMQUANTITY.oneofs_by_name['payload'].fields.append(
  _V3ITEMQUANTITY.fields_by_name['volume'])
_V3ITEMQUANTITY.fields_by_name['volume'].containing_oneof = _V3ITEMQUANTITY.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['V3ItemQuantity'] = _V3ITEMQUANTITY

V3ItemQuantity = _reflection.GeneratedProtocolMessageType('V3ItemQuantity', (_message.Message,), dict(
  DESCRIPTOR = _V3ITEMQUANTITY,
  __module__ = 'v3avs_types.V3ItemQuantity_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3ItemQuantity)
  ))
_sym_db.RegisterMessage(V3ItemQuantity)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\014ItemQuantity'))
# @@protoc_insertion_point(module_scope)
