# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3Length.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3Length.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x1av3avs_types/V3Length.proto\x12\x0bv3avs_types\"\xb7\x01\n\x08V3Length\x12\r\n\x05value\x18\x01 \x01(\x02\x12(\n\x04unit\x18\x02 \x01(\x0e\x32\x1a.v3avs_types.V3Length.Unit\"r\n\x04Unit\x12\t\n\x05METER\x10\x00\x12\r\n\tKILOMETER\x10\x01\x12\x0e\n\nCENTIMETER\x10\x02\x12\x0e\n\nMILLIMETER\x10\x03\x12\x08\n\x04INCH\x10\x04\x12\x08\n\x04SPAN\x10\x05\x12\x08\n\x04\x46OOT\x10\x06\x12\x08\n\x04YARD\x10\x07\x12\x08\n\x04MILE\x10\x08\x42-\n#com.amazon.proto.avs.v3.v3avs_typesB\x06Lengthb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3LENGTH_UNIT = _descriptor.EnumDescriptor(
  name='Unit',
  full_name='v3avs_types.V3Length.Unit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='METER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KILOMETER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CENTIMETER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MILLIMETER', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCH', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPAN', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FOOT', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YARD', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MILE', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=113,
  serialized_end=227,
)
_sym_db.RegisterEnumDescriptor(_V3LENGTH_UNIT)


_V3LENGTH = _descriptor.Descriptor(
  name='V3Length',
  full_name='v3avs_types.V3Length',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v3avs_types.V3Length.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit', full_name='v3avs_types.V3Length.unit', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _V3LENGTH_UNIT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=227,
)

_V3LENGTH.fields_by_name['unit'].enum_type = _V3LENGTH_UNIT
_V3LENGTH_UNIT.containing_type = _V3LENGTH
DESCRIPTOR.message_types_by_name['V3Length'] = _V3LENGTH

V3Length = _reflection.GeneratedProtocolMessageType('V3Length', (_message.Message,), dict(
  DESCRIPTOR = _V3LENGTH,
  __module__ = 'v3avs_types.V3Length_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3Length)
  ))
_sym_db.RegisterMessage(V3Length)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\006Length'))
# @@protoc_insertion_point(module_scope)
