# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3Level.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3avs_types import V3InventoryCount_pb2 as v3avs__types_dot_V3InventoryCount__pb2
from v3avs_types import V3Weight_pb2 as v3avs__types_dot_V3Weight__pb2
from v3avs_types import V3Volume_pb2 as v3avs__types_dot_V3Volume__pb2
from v3avs_types import V3Percentage_pb2 as v3avs__types_dot_V3Percentage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3Level.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x19v3avs_types/V3Level.proto\x12\x0bv3avs_types\x1a\"v3avs_types/V3InventoryCount.proto\x1a\x1av3avs_types/V3Weight.proto\x1a\x1av3avs_types/V3Volume.proto\x1a\x1ev3avs_types/V3Percentage.proto\"\xc7\x01\n\x07V3Level\x12.\n\x05\x63ount\x18\x01 \x01(\x0b\x32\x1d.v3avs_types.V3InventoryCountH\x00\x12\'\n\x06weight\x18\x02 \x01(\x0b\x32\x15.v3avs_types.V3WeightH\x00\x12\'\n\x06volume\x18\x03 \x01(\x0b\x32\x15.v3avs_types.V3VolumeH\x00\x12/\n\npercentage\x18\x04 \x01(\x0b\x32\x19.v3avs_types.V3PercentageH\x00\x42\t\n\x07payloadB,\n#com.amazon.proto.avs.v3.v3avs_typesB\x05Levelb\x06proto3')
  ,
  dependencies=[v3avs__types_dot_V3InventoryCount__pb2.DESCRIPTOR,v3avs__types_dot_V3Weight__pb2.DESCRIPTOR,v3avs__types_dot_V3Volume__pb2.DESCRIPTOR,v3avs__types_dot_V3Percentage__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_V3LEVEL = _descriptor.Descriptor(
  name='V3Level',
  full_name='v3avs_types.V3Level',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='v3avs_types.V3Level.count', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='v3avs_types.V3Level.weight', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='v3avs_types.V3Level.volume', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='percentage', full_name='v3avs_types.V3Level.percentage', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='v3avs_types.V3Level.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=167,
  serialized_end=366,
)

_V3LEVEL.fields_by_name['count'].message_type = v3avs__types_dot_V3InventoryCount__pb2._V3INVENTORYCOUNT
_V3LEVEL.fields_by_name['weight'].message_type = v3avs__types_dot_V3Weight__pb2._V3WEIGHT
_V3LEVEL.fields_by_name['volume'].message_type = v3avs__types_dot_V3Volume__pb2._V3VOLUME
_V3LEVEL.fields_by_name['percentage'].message_type = v3avs__types_dot_V3Percentage__pb2._V3PERCENTAGE
_V3LEVEL.oneofs_by_name['payload'].fields.append(
  _V3LEVEL.fields_by_name['count'])
_V3LEVEL.fields_by_name['count'].containing_oneof = _V3LEVEL.oneofs_by_name['payload']
_V3LEVEL.oneofs_by_name['payload'].fields.append(
  _V3LEVEL.fields_by_name['weight'])
_V3LEVEL.fields_by_name['weight'].containing_oneof = _V3LEVEL.oneofs_by_name['payload']
_V3LEVEL.oneofs_by_name['payload'].fields.append(
  _V3LEVEL.fields_by_name['volume'])
_V3LEVEL.fields_by_name['volume'].containing_oneof = _V3LEVEL.oneofs_by_name['payload']
_V3LEVEL.oneofs_by_name['payload'].fields.append(
  _V3LEVEL.fields_by_name['percentage'])
_V3LEVEL.fields_by_name['percentage'].containing_oneof = _V3LEVEL.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['V3Level'] = _V3LEVEL

V3Level = _reflection.GeneratedProtocolMessageType('V3Level', (_message.Message,), dict(
  DESCRIPTOR = _V3LEVEL,
  __module__ = 'v3avs_types.V3Level_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3Level)
  ))
_sym_db.RegisterMessage(V3Level)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\005Level'))
# @@protoc_insertion_point(module_scope)
