# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3Percentage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3Percentage.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x1ev3avs_types/V3Percentage.proto\x12\x0bv3avs_types\"\x1d\n\x0cV3Percentage\x12\r\n\x05value\x18\x01 \x01(\rB1\n#com.amazon.proto.avs.v3.v3avs_typesB\nPercentageb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_V3PERCENTAGE = _descriptor.Descriptor(
  name='V3Percentage',
  full_name='v3avs_types.V3Percentage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v3avs_types.V3Percentage.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['V3Percentage'] = _V3PERCENTAGE

V3Percentage = _reflection.GeneratedProtocolMessageType('V3Percentage', (_message.Message,), dict(
  DESCRIPTOR = _V3PERCENTAGE,
  __module__ = 'v3avs_types.V3Percentage_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3Percentage)
  ))
_sym_db.RegisterMessage(V3Percentage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\nPercentage'))
# @@protoc_insertion_point(module_scope)
