# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3RangeDelta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3RangeDelta.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x1ev3avs_types/V3RangeDelta.proto\x12\x0bv3avs_types\"L\n\x0cV3RangeDelta\x12!\n\x19range_value_delta_default\x18\x01 \x01(\x08\x12\x19\n\x11range_value_delta\x18\x02 \x01(\x01\x42\x31\n#com.amazon.proto.avs.v3.v3avs_typesB\nRangeDeltab\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_V3RANGEDELTA = _descriptor.Descriptor(
  name='V3RangeDelta',
  full_name='v3avs_types.V3RangeDelta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='range_value_delta_default', full_name='v3avs_types.V3RangeDelta.range_value_delta_default', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range_value_delta', full_name='v3avs_types.V3RangeDelta.range_value_delta', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['V3RangeDelta'] = _V3RANGEDELTA

V3RangeDelta = _reflection.GeneratedProtocolMessageType('V3RangeDelta', (_message.Message,), dict(
  DESCRIPTOR = _V3RANGEDELTA,
  __module__ = 'v3avs_types.V3RangeDelta_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3RangeDelta)
  ))
_sym_db.RegisterMessage(V3RangeDelta)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\nRangeDelta'))
# @@protoc_insertion_point(module_scope)
