# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3Range.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3Range.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x19v3avs_types/V3Range.proto\x12\x0bv3avs_types\"\x1e\n\x07V3Range\x12\x13\n\x0brange_value\x18\x01 \x01(\x01\x42,\n#com.amazon.proto.avs.v3.v3avs_typesB\x05Rangeb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_V3RANGE = _descriptor.Descriptor(
  name='V3Range',
  full_name='v3avs_types.V3Range',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='range_value', full_name='v3avs_types.V3Range.range_value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['V3Range'] = _V3RANGE

V3Range = _reflection.GeneratedProtocolMessageType('V3Range', (_message.Message,), dict(
  DESCRIPTOR = _V3RANGE,
  __module__ = 'v3avs_types.V3Range_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3Range)
  ))
_sym_db.RegisterMessage(V3Range)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\005Range'))
# @@protoc_insertion_point(module_scope)
