# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3Temperature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3Temperature.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x1fv3avs_types/V3Temperature.proto\x12\x0bv3avs_types\"\xbf\x01\n\rV3Temperature\x12\r\n\x05value\x18\x01 \x01(\x02\x12/\n\x05scale\x18\x02 \x01(\x0e\x32 .v3avs_types.V3Temperature.Scale\"n\n\x05Scale\x12\x0b\n\x07\x43\x45LSIUS\x10\x00\x12\x0e\n\nFAHRENHEIT\x10\x01\x12\n\n\x06KELVIN\x10\x02\x12\x0b\n\x07\x44\x65lisle\x10\x03\x12\n\n\x06Newton\x10\x04\x12\x0b\n\x07Rankine\x10\x05\x12\x0b\n\x07Reaumur\x10\x06\x12\t\n\x05Romer\x10\x07\x42\x32\n#com.amazon.proto.avs.v3.v3avs_typesB\x0bTemperatureb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3TEMPERATURE_SCALE = _descriptor.EnumDescriptor(
  name='Scale',
  full_name='v3avs_types.V3Temperature.Scale',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CELSIUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAHRENHEIT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KELVIN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Delisle', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Newton', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Rankine', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Reaumur', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Romer', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=130,
  serialized_end=240,
)
_sym_db.RegisterEnumDescriptor(_V3TEMPERATURE_SCALE)


_V3TEMPERATURE = _descriptor.Descriptor(
  name='V3Temperature',
  full_name='v3avs_types.V3Temperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v3avs_types.V3Temperature.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale', full_name='v3avs_types.V3Temperature.scale', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _V3TEMPERATURE_SCALE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=240,
)

_V3TEMPERATURE.fields_by_name['scale'].enum_type = _V3TEMPERATURE_SCALE
_V3TEMPERATURE_SCALE.containing_type = _V3TEMPERATURE
DESCRIPTOR.message_types_by_name['V3Temperature'] = _V3TEMPERATURE

V3Temperature = _reflection.GeneratedProtocolMessageType('V3Temperature', (_message.Message,), dict(
  DESCRIPTOR = _V3TEMPERATURE,
  __module__ = 'v3avs_types.V3Temperature_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3Temperature)
  ))
_sym_db.RegisterMessage(V3Temperature)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\013Temperature'))
# @@protoc_insertion_point(module_scope)
