# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3avs_types/V3Volume.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3avs_types/V3Volume.proto',
  package='v3avs_types',
  syntax='proto3',
  serialized_pb=_b('\n\x1av3avs_types/V3Volume.proto\x12\x0bv3avs_types\"\x90\x05\n\x08V3Volume\x12\r\n\x05value\x18\x01 \x01(\x02\x12(\n\x04unit\x18\x02 \x01(\x0e\x32\x1a.v3avs_types.V3Volume.Unit\"\xca\x04\n\x04Unit\x12\t\n\x05LITER\x10\x00\x12\x0e\n\nMILLILITER\x10\x01\x12\x0c\n\x08TEASPOON\x10\x02\x12\x0f\n\x0bUK_TEASPOON\x10\x03\x12\x0f\n\x0b\x41U_TEASPOON\x10\x04\x12\x14\n\x10\x43UBIC_CENTIMETER\x10\x05\x12\x0f\n\x0b\x43UBIC_METER\x10\x06\x12\r\n\tUK_GALLON\x10\x07\x12\x0c\n\x08UK_QUART\x10\x08\x12\x0b\n\x07UK_PINT\x10\t\x12\n\n\x06UK_CUP\x10\n\x12\x0b\n\x07UK_GILL\x10\x0b\x12\x0c\n\x08UK_OUNCE\x10\x0c\x12\x0b\n\x07UK_DRAM\x10\r\x12\x13\n\x0fUS_FLUID_GALLON\x10\x0e\x12\x12\n\x0eUS_FLUID_QUART\x10\x0f\x12\x11\n\rUS_FLUID_PINT\x10\x10\x12\x10\n\x0cUS_FLUID_CUP\x10\x11\x12\x12\n\x0eUS_FLUID_OUNCE\x10\x12\x12\x11\n\rUS_TABLESPOON\x10\x13\x12\x0f\n\x0bUS_TEASPOON\x10\x14\x12\x0b\n\x07US_DRAM\x10\x15\x12\x11\n\rUS_DRY_GALLON\x10\x16\x12\x10\n\x0cUS_DRY_QUART\x10\x17\x12\x0f\n\x0bUS_DRY_PINT\x10\x18\x12\x0e\n\nUS_DRY_CUP\x10\x19\x12\x10\n\x0cUS_DRY_OUNCE\x10\x1a\x12\x0e\n\nCUBIC_INCH\x10\x1b\x12\x0e\n\nCUBIC_FOOT\x10\x1c\x12\x0e\n\nCUBIC_YARD\x10\x1d\x12\x0e\n\nMETRIC_CUP\x10\x1e\x12\x13\n\x0fMETRIC_TEASPOON\x10\x1f\x12\x11\n\rUK_FLUID_DRAM\x10 \x12\x12\n\x0eUK_FLUID_OUNCE\x10!\x12\x0b\n\x07US_GILL\x10\"B-\n#com.amazon.proto.avs.v3.v3avs_typesB\x06Volumeb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_V3VOLUME_UNIT = _descriptor.EnumDescriptor(
  name='Unit',
  full_name='v3avs_types.V3Volume.Unit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LITER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MILLILITER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEASPOON', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_TEASPOON', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AU_TEASPOON', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUBIC_CENTIMETER', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUBIC_METER', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_GALLON', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_QUART', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_PINT', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_CUP', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_GILL', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_OUNCE', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_DRAM', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_FLUID_GALLON', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_FLUID_QUART', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_FLUID_PINT', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_FLUID_CUP', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_FLUID_OUNCE', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_TABLESPOON', index=19, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_TEASPOON', index=20, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_DRAM', index=21, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_DRY_GALLON', index=22, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_DRY_QUART', index=23, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_DRY_PINT', index=24, number=24,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_DRY_CUP', index=25, number=25,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_DRY_OUNCE', index=26, number=26,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUBIC_INCH', index=27, number=27,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUBIC_FOOT', index=28, number=28,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUBIC_YARD', index=29, number=29,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METRIC_CUP', index=30, number=30,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METRIC_TEASPOON', index=31, number=31,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_FLUID_DRAM', index=32, number=32,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UK_FLUID_OUNCE', index=33, number=33,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='US_GILL', index=34, number=34,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=114,
  serialized_end=700,
)
_sym_db.RegisterEnumDescriptor(_V3VOLUME_UNIT)


_V3VOLUME = _descriptor.Descriptor(
  name='V3Volume',
  full_name='v3avs_types.V3Volume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v3avs_types.V3Volume.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit', full_name='v3avs_types.V3Volume.unit', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _V3VOLUME_UNIT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=700,
)

_V3VOLUME.fields_by_name['unit'].enum_type = _V3VOLUME_UNIT
_V3VOLUME_UNIT.containing_type = _V3VOLUME
DESCRIPTOR.message_types_by_name['V3Volume'] = _V3VOLUME

V3Volume = _reflection.GeneratedProtocolMessageType('V3Volume', (_message.Message,), dict(
  DESCRIPTOR = _V3VOLUME,
  __module__ = 'v3avs_types.V3Volume_pb2'
  # @@protoc_insertion_point(class_scope:v3avs_types.V3Volume)
  ))
_sym_db.RegisterMessage(V3Volume)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.amazon.proto.avs.v3.v3avs_typesB\006Volume'))
# @@protoc_insertion_point(module_scope)
