configName: pic32mzda_curiosity
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../Harmony_public_release
processor: PIC32MZ2064DAR176
projectName: ''
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;bt;core;crypto;csp;csp_apps_pic32cm_mc00;csp_apps_sam_c20_c21;gfx;gfx_apps;net;touch;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.3.111\atdf\PIC32MZ2064DAR176.atdf
