format_version: v1.0
configName: pic32mzda_curiosity
folderName: pic32mz_da_curiosity
frameworkPath: C:\gitHub
processor: PIC32MZ2064DAR176
projectName: pic32mz_da_curiosity
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MZ-DA_DFP\1.4.118\atdf\PIC32MZ2064DAR176.atdf
