configName: pic32mk_gp_db
folderName: ''
format_version: v1.0
frameworkPath: D:\Projects\git_hub
processor: PIC32MK1024GPE100
projectName: ''
settings:
  PackageFilter: audio;bsp;bt;core;csp;gfx;gfx_apps;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-GP_DFP\1.4.117\atdf\PIC32MK1024GPE100.atdf
